
PrintQuests.UnsurelyNamedTrackingQuests = {
    [83281] = "Weaver Weekly turnin???",
    [86931] = "Weaver Weekly turnin / Bronze Celebration Tokens on first weekly turnin?",
    [81602] = "Severed Threads - The General: Reached Crony (2/8) reputation",
    [81626] = "Severed Threads - The General: Reached Crony (2/8) reputation",
    [81598] = "Severed Threads - The Weaver: Reached Crony (2/8) reputation",
    [81627] = "Severed Threads - The Weaver: Reached Crony (2/8) reputation",
    [80415] = "War Supply Chest on Siren Isle/Azj'kahet looted?",
    [80416] = "War Supply Chest on Siren Isle/Azj'kahet looted?",
    [84873] = "Siren Isle Rare: Kill X Rares?",
    [85714] = "Siren Isle: Rune-Sealed Coffer solved (in Stormtide Dregs)?",
    [86171] = "Siren Isle: Rune-Sealed Coffer looted (in Stormtide Dregs)?",
    [85723] = "Anniversary Worldboss: First Worldboss kill of day/week? Azuregos/Doomwalker",
    [85168] = "Anniversary Worldboss: Second Worldboss kill of day/week? Lord Kazzak",
    [84614] = "Khaz Algar Worldboss killed? Aggregation of Horrors",
    [83280] = "Related to Spark of Omens, weekly",
    [83158] = "... on Waterworks Delve completed?",
    [84819] = "Looting Zekvir Hulking Raptorial Claw in Waterworks Tier 8",
    [84818] = "Looting Zekvir Hulking Raptorial Claw in Kriegval's Rest Tier 8",
    [86325] = "Zekvirs Lair kill?",
    [85463] = "Renown: The Cartels of Undermine Level 2",
    [85089] = "Undermine Worldboss kill?",
    [89401] = "Undermine Worldboss kill?",
    [88846] = "Liberation of Undermine LFR: during Rik Reverb Trash: +100 Gallagio Loyalty Rep",
    [89479] = "Liberation of Undermine LFR: during Rik Reverb Trash: +100 Gallagio Loyalty Rep",
    [89453] = "Liberation of Undermine LFR: Cauldron of Carnage killed",
    [89454] = "Liberation of Undermine LFR: Rik Reverb killed",
    [86438] = "Skittering Breach/Excavation Site 9: The Underpin invasion",
    [86371] = "Skittering Breach/Excavation Site 9: The Underpin invasion",
    [87286] = "Excavation Site 9: The Underpin invasion (triggered), 2nd invasion that week",
}

PrintQuests.ConfidentlyNamedTrackingQuests = {
    -----------------------------------------------------------------------------------------------------------------------
    -- Darkmoon Faire
    [29484] = "Darkmoon Faire: Cooking - Putting the Crunch in the Frog",
    [29466] = "Darkmoon Faire: Fishing - Spoilin' for Salty Sea Dogs",
    [29467] = "Darkmoon Faire: Engineering - Talkin' Tonks",
    [29469] = "Darkmoon Faire: Mining - Rearm, Reuse, Recycle",
    
    -----------------------------------------------------------------------------------------------------------------------
    -- Love is in the Air
    [74957] = "Love is in the Air: Increased X-45 Heartbreaker Droprate (daily, accwide)",
    [86172] = "Love is in the Air: Increased Love Witch's Sweeper Droprate (daily, accwide)",
    
    -----------------------------------------------------------------------------------------------------------------------
    -- Timewalking
    [78204] = "Turbulent Timeways: Have 5 stacks of Mastery of Timeways",
    [85877] = "Turbulent Timeways II: Have 5 stacks of Mastery of Timeways",
    
    -----------------------------------------------------------------------------------------------------------------------
    -- Pandaria Intro
    [37186] = "The Art of War",
    [37193] = "The King's Command",
    
    -----------------------------------------------------------------------------------------------------------------------
    -- Legion Intro
    [44659] = "Skip the Legion Introductory quests",

    -----------------------------------------------------------------------------------------------------------------------
    -- Exiles Reach
    [58883] = "Stitched Leather Boots looted",
    [59139] = "Spider-Eye Ring looted",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Dragonriding Cosmetics
    [79112] = "Used Winding Slitherdrake: Lunar Festival Armor",
    [82181] = "Used Delver's Dirigible Schematic: Empennage",
    [82171] = "Used Delver's Dirigible Schematic: Wing-Mounted Propeller",
    [82183] = "Used Delver's Dirigible Schematic: Rotor Blades",
    [82167] = "Used Delver's Dirigible Schematic: Front-Mounted Propeller",
    [82187] = "Used Delver's Dirigible Schematic: Brown Paint",
    [82179] = "Used Delver's Dirigible Schematic: Exhaust",
    [82170] = "Used Delver's Dirigible Schematic: Front-Mounted Lantern",
    [82176] = "Used Delver's Dirigible Schematic: Lantern Wing",
    [82185] = "Used Delver's Dirigible Schematic: Zeppelin",
    [83308] = "Used Delver's Dirigible Schematic: Void",
    
    -----------------------------------------------------------------------------------------------------------------------
    -- Dornogal
    [85156] = "Angorla stay a while and listen",
    [85103] = "Apprentice Tanmar stay a while and listen",
    [84009] = "Alleria Stay a while and listen after The Fleet Arrives",
    [84345] = "Turalyon Stay a while and listen after Embassies and Envoys",
    [82461] = "Dagran Thaurissan II Stay a while and listen in The Archive",
    [84814] = "Dagran Thaurissan II Stay a while and listen in Vault of Memory",
    [85682] = "Magni Bronzebeard Stay a while and listen in front of The Archive",
    [82542] = "Rooktender Lufsela Stay a while and listen in front of Thrall, Shraubendre",
    [84813] = "Rooktender Lufsela Stay a while and listen in Dhar Oztan",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Severed Threads
    [84539] = "Severed Threads: Renown 22",
    -- The Vizier
    [81605] = "Severed Threads - The Vizier: Reached Acquiantance (1/8) reputation",
    [81606] = "Severed Threads - The Vizier: Reached Crony (2/8) reputation",
    [81607] = "Severed Threads - The Vizier: Reached Accomplice (3/8) reputation",
    -- missing Collaborator 4/8
    [84534] = "Severed Threads - The Vizier: Reached Accessory (5/8) reputation",
    [84535] = "Severed Threads - The Vizier: Reached Abettor (6/8) reputation",
    [84536] = "Severed Threads - The Vizier: Reached Conspirator (7/8) reputation",
    [84537] = "Severed Threads - The Vizier: Reached Mastermind (8/8) reputation",
    -- The Weaver
    [81597] = "Severed Threads - The Weaver: Reached Acquiantance (1/8) reputation",
    -- Crony 2/8 has 2 tracking quests, ref UnsurelyNamedTrackingQuests
    [81599] = "Severed Threads - The Weaver: Reached Accomplice (3/8) reputation",
    [81600] = "Severed Threads - The Weaver: Reached Collaborator (4/8) reputation",
    [84538] = "Severed Threads - The Weaver: Reached Accessory (5/8) reputation",
    -- missing Abettor 6/8
    [84540] = "Severed Threads - The Weaver: Reached Conspirator (7/8) reputation",
    [84541] = "Severed Threads - The Weaver: Reached Mastermind (8/8) reputation",
    -- The General
    [81601] = "Severed Threads - The General: Reached Acquiantance (1/8) reputation",
    -- Crony 2/8 has 2 tracking quests, ref UnsurelyNamedTrackingQuests
    [81603] = "Severed Threads - The General: Reached Accomplice (3/8) reputation",
    [81604] = "Severed Threads - The General: Reached Collaborator (4/8) reputation",
    [84530] = "Severed Threads - The General: Reached Accessory (5/8) reputation",
    [84531] = "Severed Threads - The General: Reached Abettor (6/8) reputation",
    [84532] = "Severed Threads - The General: Reached Conspirator (7/8) reputation",
    [84533] = "Severed Threads - The General: Reached Mastermind (8/8) reputation",
    [80545] = "Severed Threads: Weekly Pact selected: The General",
    [80544] = "Severed Threads: Weekly Pact selected: The Weaver",
    [80546] = "Severed Threads: Weekly Pact selected: The Vizier",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Awakening The Machine
    [84631] = "Awakening The Machine: Wave 5/20 cleared",
    [84632] = "Awakening The Machine: Wave 10/20 cleared",
    [84633] = "Awakening The Machine: Wave 15/20 cleared",
    [84634] = "Awakening The Machine: Wave 20/20 cleared",
    [84644] = "Awakening The Machine: Awakened Cache looted (right)",
    [84642] = "Awakening The Machine: Awakened Cache looted (front left)",
    [84646] = "Awakening The Machine: Awakened Cache looted (back left)",
    [84647] = "Awakening The Machine: Awakened Cache looted (back center)",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Mining
    [83054] = "Mining: Slab of Slate 1/5 looted (weekly)",
    [83053] = "Mining: Slab of Slate 2/5 looted (weekly)",
    [83052] = "Mining: Slab of Slate 3/5 looted (weekly)",
    [83051] = "Mining: Slab of Slate 4/5 looted (weekly)",
    [83050] = "Mining: Slab of Slate 5/5 looted (weekly)",
    [83049] = "Mining: Erosion-Polished Slate looted (weekly)",
    [80368] = "Mining: First camouflaged Bismuth looted",
    [80370] = "Mining: First camouflaged Ironclaw looted",
    [80369] = "Mining: First camouflaged Aqirite looted",
    [80358] = "Mining: First Ironclaw Seam looted",
    [80357] = "Mining: First Aqirite Seam looted",
    [80355] = "Mining: First Rich Ironclaw looted",
    [80367] = "Mining: First EZ-Mine Ironclaw looted",
    [80373] = "Mining: First Webbed Ironclaw looted",
    [83907] = "Mining: Dornogal Chisel treasure looted",
    [81391] = "Mining Book: Exceptional Miner's Notes used",
    [83062] = "Mining Book: Machine-Learned Mining Notes used",
    [81392] = "Mining Book: Pristine Miner's Notes used",
    [83733] = "Mining Book: Algari Treatise on Mining used weekly",
    [82614] = "Mining Book: A Rocky Start used",
    [82317] = "Mastering the Mysterious: Unlocked 2nd Charge of Overload Empowered Deposit",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Engineering
    [83261] = "Engineering: Earthen Induction Coil looted (weekly)",
    [83260] = "Engineering: Rust-Locked Mechanism looted (weekly)",
    [84229] = "Engineering Book: Faded Engineer Scriblings used",
    [83063] = "Engineering Book: Machine-Learned Engineering Notes used",
    [84230] = "Engineering Book: Exceptional Engineer's Notes used",
    [84231] = "Engineering Book: Pristine Engineer's Scribblings used",
    [83728] = "Engineering Book: Algari Treatise on Engineering used weekly",
    [81355] = "Engineering First Time Craft: Convincingly Realistic Jumper Cables",
    [81356] = "Engineering First Time Craft: Algari Repair Bot 11O",
    [81319] = "Engineering First Time Craft: Bismuth Miner's Headgear",
    [81293] = "Engineering First Time Craft: Algari Competitor's Plate Goggles",
    [81387] = "Engineering First Time Craft: Dredger's Goggles",
    [81365] = "Engineering First Time Craft: Spelunker's Goggles",
    [81364] = "Engineering First Time Craft: Acolyte's Goggles",
    [81352] = "Engineering First Time Craft: Energy Redistribution Beacon",
    [81353] = "Engineering First Time Craft: Irresistable Red Button",
    [81329] = "Engineering First Time Craft: Chaos Circuit",
    [81342] = "Engineering First Time Craft: Serrated Cogwheel",
    [81350] = "Engineering First Time Craft: Pouch of Pocket Grenades",
    [81388] = "Engineering First Time Craft: 4UT0-41M3R",
    [81311] = "Engineering First Time Craft: Spring-Loaded Bismuth Fabric Cutters",
    [81332] = "Engineering First Time Craft: Potion Bomb of Recovery",
    [81347] = "Engineering First Time Craft: Blame Redirection Device",
    [81315] = "Engineering First Time Craft: Bismuth Fisherfriend",
    [81345] = "Engineering First Time Craft: Adjustable Cogwheel",
    [81313] = "Engineering First Time Craft: Bismuth Brainwave Projector",
    [81349] = "Engineering First Time Craft: Complicated Fuse Box",
    [81317] = "Engineering First Time Craft: Lapidary's Bismuth Clamps",
    [81331] = "Engineering First Time Craft: Potion Bomb of Speed",
    [81290] = "Engineering First Time Craft: Algari Competitor's Cloth Goggles",
    [81308] = "Engineering First Time Craft: Venting Vambraces",
    [81346] = "Engineering First Time Craft: Recalibrated Safety Switch",
    [81343] = "Engineering First Time Craft: Overclocked Cogwheel",
    [81351] = "Engineering First Time Craft: Concealed Chaos Module",
    [81320] = "Engineering First Time Craft: Aqirite Miner's Headgear",
    [81324] = "Engineering First Time Craft: Miner's Aqirite Hoard",
    [81316] = "Engineering First Time Craft: Aqirite Fisherfriend",
    [81341] = "Engineering First Time Craft: P.0.W. x2",
    [81314] = "Engineering First Time Craft: Aqirite Brainwave Projector",
    [81307] = "Engineering First Time Craft: Blasting Bracers",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Leatherworking
    [80913] = "Leatherworking First Time Craft: Spelunker's Leather Bands",
    [80907] = "Leatherworking First Time Craft: Spelunker's Leather Footpads",
    [80906] = "Leatherworking First Time Craft: Spelunker's Leather Jerkin",
    [80921] = "Leatherworking First Time Craft: Tracker's Chitin Cuffs",
    [80915] = "Leatherworking First Time Craft: Tracker's Chitin Galoshes",
    [80914] = "Leatherworking First Time Craft: Tracker's Chitin Hauberk",
    [80942] = "Leatherworking First Time Craft: Hideseeker's Hat",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- 20th Anniversary
    [86282] = "20th Anniversary Blackrock Depths Miniboss: Pyromancer Loregrain killed LFR",
    [86285] = "20th Anniversary Blackrock Depths Miniboss: Pyromancer Loregrain killed Normal",
    [86278] = "20th Anniversary Blackrock Depths Miniboss: High Interrogator Gerstahn killed LFR",
    [86289] = "20th Anniversary Blackrock Depths Miniboss: High Interrogator Gerstahn killed Normal",
    [86290] = "20th Anniversary Blackrock Depths Miniboss: High Interrogator Gerstahn killed Heroic",
    [86279] = "20th Anniversary Blackrock Depths Miniboss: Houndmaster Grebmar killed LFR",
    [86288] = "20th Anniversary Blackrock Depths Miniboss: Houndmaster Grebmar killed Normal",
    [86291] = "20th Anniversary Blackrock Depths Miniboss: Houndmaster Grebmar killed Heroic",
    [86280] = "20th Anniversary Blackrock Depths Miniboss: Fineous Darkvire killed LFR",
    [86287] = "20th Anniversary Blackrock Depths Miniboss: Fineous Darkvire killed Normal",
    [86292] = "20th Anniversary Blackrock Depths Miniboss: Fineous Darkvire killed Heroic",
    [86281] = "20th Anniversary Blackrock Depths Miniboss: Phalanx killed LFR",
    [86286] = "20th Anniversary Blackrock Depths Miniboss: Phalanx killed Normal",
    [86293] = "20th Anniversary Blackrock Depths Miniboss: Phalanx killed Heroic",
    [84665] = "20th Anniversary: The Originals / Timely Gate Crashers turnin",
    [60214] = "Anniversary Worldboss: Doomwalker Kill",
    [84282] = "Anniversary Worldboss: Sha of Anger Kill",
    [84256] = "Anniversary Worldboss: Archavon the Stone Watcher Kill",
    [47462] = "Anniversary Worldboss: Azuregos Kill",
    [47461] = "Anniversary Worldboss: Lord Kazzak Kill",
    [47463] = "Anniversary Worldboss: Dragon of Nightmare Kill",
    [86202] = "Opened first Bronze Celebration Chest of the week",
    [85661] = "Bought first T2 Set",
    [85828] = "Bought second T2 Set",
    [85841] = "Learned Death Knight T2 Set",
    [85842] = "Learned Demon Hunter T2 Set",
    [85843] = "Learned Druid T2 Set",
    [85844] = "Learned Evoker T2 Set",
    [85845] = "Learned Hunter T2 Set",
    [85846] = "Learned Mage T2 Set",
    [85847] = "Learned Monk T2 Set",
    [85848] = "Learned Paladin T2 Set",
    [85849] = "Learned Priest T2 Set",
    [85850] = "Learned Rogue T2 Set",
    [85851] = "Learned Shaman T2 Set",
    [85852] = "Learned Warlock T2 Set",
    [85853] = "Learned Warrior T2 Set",
    [83831] = "Guest Relations completed Tutorial (A Whiff of Help) (accwide)",
    [85414] = "Guest Relations Pirate Gastronomy: Asked Maru about Rogue's thistle",
    [85415] = "Guest Relations Pirate Gastronomy: Asked Maru about Banana rum berries",
    [85416] = "Guest Relations Pirate Gastronomy: Asked Maru about Fire breathing chill sacs",
    [85417] = "Guest Relations Pirate Gastronomy: Asked Maru about Koatini's oil",
    [85418] = "Guest Relations Pirate Gastronomy: Asked Maru about Deadwind catfish",
    [85419] = "Guest Relations Pirate Gastronomy: Asked Maru about Giant growth fish",
    [85420] = "Guest Relations Pirate Gastronomy: Asked Maru about Sholazar nettles",
    [85421] = "Guest Relations Pirate Gastronomy: Asked Maru about Highland crawdaddies",
    [85411] = "Guest Relations Pirate Gastronomy: Asking Bonenose about Cooktholomew",
    [83824] = "Restoring A Grand Tale - Crafted Green Hills of Stranglethorn",
    [84617] = "Alyx enabled harder challenges - unlock call board",
    [83790] = "Celebration Crate #1 - Opened Gerald",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Isle of Dorn
    [79685] = "Isle of Dorn Rare: Sandres the Relicbearer killed daily",
    [81892] = "Isle of Dorn Rare: Springbubble killed daily",
    [81893] = "Isle of Dorn Rare: Bloodmaw killed daily",
    [81894] = "Isle of Dorn Rare: Warphorn killed daily",
    [81907] = "Isle of Dorn Rare: Escaped Cutthroat killed daily",
    [84029] = "Isle of Dorn Rare: Escaped Cutthroat killed weekly reputation",
    [81897] = "Isle of Dorn Rare: Plaguehart killed daily",
    [84026] = "Isle of Dorn Rare: Plaguehart killed weekly reputation",
    [81899] = "Isle of Dorn Rare: Gar'loc killed daily",
    [84028] = "Isle of Dorn Rare: Gar'loc killed weekly reputation",
    [81921] = "Isle of Dorn Rare: Matriarch Charfuria killed daily",
    [81921] = "Isle of Dorn Rare: Matriarch Charfuria killed weekly reputation",
    [81920] = "Isle of Dorn Rare: Clawbreaker K'zithix killed daily",
    [84036] = "Isle of Dorn Rare: Clawbreaker K'zithix killed weekly reputation",
    [81905] = "Isle of Dorn Rare: Flamekeeper Graz killed daily",
    [84034] = "Isle of Dorn Rare: Flamekeeper Graz killed weekly reputation",
    [82204] = "Isle of Dorn Rare: Kereke killed daily",
    [85160] = "Isle of Dorn Rare: Kereke killed weekly reputation",
    [81902] = "Isle of Dorn Rare: Kronolith, Might of the Mountain killed daily",
    [84031] = "Isle of Dorn Rare: Kronolith, Might of the Mountain killed weekly reputation",
    [82205] = "Isle of Dorn Rare: Rotfist killed daily",
    [85161] = "Isle of Dorn Rare: Rotfist killed weekly reputation",
    [81901] = "Isle of Dorn Rare: Tempest Lord Incarnus killed daily",
    [84030] = "Isle of Dorn Rare: Tempest Lord Incarnus killed weekly reputation",
    [84032] = "Isle of Dorn Rare: Shallowshell the Clacker killed weekly reputation",
    [81922] = "Isle of Dorn Rare: Sweetspark the Oozful killed daily",
    [84038] = "Isle of Dorn Rare: Sweetspark the Oozeful killed weekly reputation",
    [81923] = "Isle of Dorn Rare: Tephratennae killed daily",
    [84037] = "Isle of Dorn Rare: Tephratennae killed weekly reputation",
    [81904] = "Isle of Dorn Rare: Twice-Stinger the Wretched killed daily",
    [84033] = "Isle of Dorn Rare: Twice-Stinger the Wretched killed weekly reputation",
    [85159] = "Isle of Dorn Rare: Zovex killed weekly reputation",
    [78619] = "Isle of Dorn Rare: Rustual Titancap killed daily",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Ringing Deeps
    [80003] = "Ringing Deeps Rare: Disturbed Earthgorger killed daily",
    [84050] = "Ringing Deeps Rare: Disturbed Earthgorger killed weekly reputation",
    [81562] = "Ringing Deeps Rare: Charmonger Rare killed daily",
    [84044] = "Ringing Deeps Rare: Charmonger Rare killed weekly reputation",
    [81511] = "Ringing Deeps Rare: Coalesced Monstrosity Rare killed daily",
    [84045] = "Ringing Deeps Rare: Coalesced Monstrosity Rare killed weekly reputation",
    [82464] = "Ringing Deeps Chest: Dusty Prospector Chest looted",
    [82820] = "Ringing Deeps Chest: Blocked Intake looted",
    [83253] = "Ringing Deeps Chest: Pile of Refuse looted",
    [82052] = "Ringing Deeps: Submerged Sign interacted",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Hallowfall
    [81881] = "Hallowfall Rare: Funglour killed daily",
    [82066] = "Hallowfall: A Scout's Journal interacted",
    [79081] = "Hallowfall: Flamegard's Hope Achievement daily lockout",
    [81972] = "Hallowfall: Windswept Satchel near Priory of the Sacred Flame looted",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Azj'kahet
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Siren Isle
    [84801] = "Siren Isle Rare: Ghostmaker killed daily",
    [84792] = "Siren Isle Rare: Ikir the Flotsurge killed daily",
    [85403] = "Siren Isle Rare: Tempest Talon killed daily",
    [84798] = "Siren Isle Rare: Slaughtershell killed daily",
    [85405] = "Siren Isle Rare: Zek'hul the shipbreaker killed daily",
    [85404] = "Siren Isle Rare: Brinebough killed daily",
    [84805] = "Siren Isle Rare: Asbjorn the Bloodsoaked killed daily",
    [84794] = "Siren Isle Rare: Wreckwater killed daily",
    [85406] = "Siren Isle Rare: Ksvir the Forgotten killed daily",
    [86933] = "Siren Isle Rare: Snacker killed daily",
    [84796] = "Siren Isle Rare: Grimmgull killed daily",
    [84797] = "Siren Isle Rare: Gunnlord the Sea-Drinker killed daily",
    [84803] = "Siren Isle Rare: Siris the Sea Scorpion killed daily",
    [84802] = "Siren Isle Rare: Coralweaver Calliso killed daily",
    [84795] = "Siren Isle Rare: Bloodbrine killed daily",
    [86779] = "Siren Isle Rare: Shardsong killed daily",
    [84799] = "Siren Isle Rare: Plank-Master Bluebelly daily",
    [84800] = "Siren Isle Rare: Chef Chum Platter daily",
    [86732] = "Siren Isle Chest: Stone Carvers Scramseax looted",
    [86566] = "Siren Isle Quest: Snapdragon Progress Update (24h lockout)",
    [86485] = "Siren Isle Quest: complete A Loyal Friend questchain",
    [86373] = "Siren Isle Loot: Teal Snapdragon Treat",
    [85669] = "Siren Isle: obtained Thunderlord's Crackling Citrine - vendor unlock",
    [85670] = "Siren Isle: obtained Undersea Overseer's Citrine - vendor unlock",
    [85671] = "Siren Isle: obtained Squall Sailor's Citrine - vendor unlock",
    [85672] = "Siren Isle: obtained Mariner's Hallowed Citrine - vendor unlock",
    [85673] = "Siren Isle: obtained Old Salt's Bardic Citrine - vendor unlock",
    [85674] = "Siren Isle: obtained Storm Sewer's Citrine - vendor unlock",
    [85675] = "Siren Isle: obtained Windsinger's Runed Citrine - vendor unlock",
    [85676] = "Siren Isle: obtained Stormbringer's Runed Citrine - vendor unlock",
    [85677] = "Siren Isle: obtained Fathomdweller's Runed Citrine - vendor unlock",
    [85707] = "Siren Isle: obtained Legendary Skipper's Citrine - vendor unlock",
    [85708] = "Siren Isle: obtained Seabed Leviathan's Citrine - vendor unlock",
    [85709] = "Siren Isle: obtained Roaring War-Queen's Citrine - vendor unlock",
    [85799] = "Siren Isle Thrayir: Turbulent Runestone used",
    [85800] = "Siren Isle Thrayir: Cyclonic Runestone used",
    [85801] = "Siren Isle Thrayir: Torrential Runestone used",
    [85802] = "Siren Isle Thrayir: Whirling Runestone used",
    [85803] = "Siren Isle Thrayir: Thunderous Runestone used",
    [86532] = "Ensemble: Bilgeswabby's Garb",
    [86533] = "Ensemble: Pilfered Mariner's Garb",
    [86534] = "Ensemble: Salt-Stained Garb",
    [86498] = "Ensemble: Rune Scribe's Vestments",
    [86499] = "Ensemble: Bloodscout Outfit",
    [86500] = "Ensemble: Hydraflayer Regalia",
    [86501] = "Ensemble: Tidecrasher Armor",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Undermine
    [85494] = "Undermine Chest: Marooned Floatmingo",
    [85426] = "Undermine Chest: Potent Potable",
    [85495] = "Undermine Chest: Uncracked Cold Ones",
    [85496] = "Undermine Chest: Trick Deck of Cards",
    [85492] = "Undermine Chest: Particularly Nice Lamp",
    [84954] = "Blackwater Cartel Contract selected (warband wide, weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Delves
    [82945] = "Bountiful Waterworks completed (daily)",
    [82938] = "Bountiful The Dread Pit completed (daily)",
    [82937] = "Bountiful The Sinkhole completed (daily)",
    [82776] = "Bountiful Tak-Rethan Abyss completed (daily)",
    [82944] = "Bountiful Earthcrawl Mines completed (daily)",
    [82777] = "Bountiful Nightfall Sanctum completed (treasure room opened) (daily)",
    [82942] = "Bountiful The Spiral Weave completed (daily)",
    [82943] = "Bountiful The Underkeep completed (daily)",
    [82941] = "Bountiful Kriegval's Rest completed (daily)",
    [83319] = "Bountiful Excavation Site 9 completed (daily)",
    [83318] = "Assembly of the Deeps Rep bonus on delve complete (weekly?)",
    [83320] = "Hallowfall Arathi Rep bonus on delve complete (weekly?)",
    [83456] = "The Waterworks - Sturdy Chest near Waxface looted (warband wide, onetime)",
    [83456] = "Earthcrawl Mines - Sturdy Chest near Web General Ab'enar looted (warband wide, onetime)",
    [83456] = "Earthcrawl Mines - Sturdy Chest: In square shaped room looted (warband wide, onetime)",
    [83679] = "Skittering Breach - Sturdy Chest in first building looted (warband wide, onetime)",
    [83663] = "The Underkeep - Sturdy Chest in passage between left and bottom room looted (warband wide, onetime)",
    [83663] = "The Underkeep - Sturdy Chest in Researcher Ven'kex room looted (warband wide, onetime)",
    [83691] = "Myromancer Cavern - Sturdy Chest under water looted (warband wide, onetime)",
    [83672] = "Myromancer Cavern - Sturdy Chest on rock inside water looted (warband wide, onetime)",
    [83455] = "Myromancer Cavern - Sturdy Chest in top right corner of map looted (warband wide, onetime)",
    [83455] = "Fungal Folly - Sturdy Chest in top right corner of map looted (warband wide, onetime)",
    [83651] = "Tak-Rethan Abyss - Sturdy Chest above water entrance looted (warband wide, onetime)",
    [83669] = "Tak-Rethan Abyss - Sturdy Chest on left side of map looted (warband wide, onetime)",
    [83686] = "Tak-Rethan Abyss - Sturdy Chest on coral looted (warband wide, onetime)",
    [83688] = "Nightfall Sanctum - Sturdy Chest next to entrance looted (warband wide, onetime)",
    [86788] = "Sidestreet Sluice - Sturdy Chest in treasure room looted (warband wide, onetime)",
    [84101] = "Brann reached Level 40 (warband wide, onetime)",
    [84102] = "Brann reached Level 41 (warband wide, onetime)",
    [84103] = "Brann reached Level 42 (warband wide, onetime)",
    [84104] = "Brann reached Level 43 (warband wide, onetime)",
    [84105] = "Brann reached Level 44 (warband wide, onetime)",
    [84106] = "Brann reached Level 45 (warband wide, onetime)",
    [84107] = "Brann reached Level 46 (warband wide, onetime)",
    [84108] = "Brann reached Level 47 (warband wide, onetime)",
    [84109] = "Brann reached Level 48 (warband wide, onetime)",
    [84110] = "Brann reached Level 49 (warband wide, onetime)",
    [83329] = "Brann reached Level 50 (warband wide, onetime)",
    [86324] = "Zekvirs Lair Tier 2 kill (weekly)",
    [86328] = "Delver's Starter Kit bought",
    [86329] = "Delver's Cosmetic Surprise Bag bought",
    [85204] = "Delver's Journey Season 2: Delver's Dirigible Schematic: Flamethrower",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Misc
    [39751] = "Classic Timewalking LFG completion",
    [84736] = "First Restored Coffer Key looted of the week",
    [84737] = "Second Restored Coffer Key looted of the week",
    [84738] = "Third Restored Coffer Key looted of the week",
    [84739] = "Fourth Restored Coffer Key looted of the week",
    
    -- -----------------------------------------------------------------------------------------------------------------------
    -- Mythic+
    [85469] = "First weekly completion of an 8+ Mythic Dungeon",
}
