
PrintQuests.UnsurelyNamedTrackingQuests = {
    [83281] = "Weaver Weekly turnin???",
    [86931] = "Weaver Weekly turnin / Bronze Celebration Tokens on first weekly turnin?",
    [81602] = "Severed Threads - The General: Reached Crony (2/8) reputation",
    [81626] = "Severed Threads - The General: Reached Crony (2/8) reputation",
    [81598] = "Severed Threads - The Weaver: Reached Crony (2/8) reputation",
    [81627] = "Severed Threads - The Weaver: Reached Crony (2/8) reputation",
    [80415] = "War Supply Chest on Siren Isle/Azj'kahet looted?",
    [80416] = "War Supply Chest on Siren Isle/Azj'kahet looted?",
    [84873] = "Siren Isle Rare: Kill X Rares?",
    [85714] = "Siren Isle: Rune-Sealed Coffer solved (in Stormtide Dregs)?",
    [86171] = "Siren Isle: Rune-Sealed Coffer looted (in Stormtide Dregs)?",
    [85723] = "Anniversary Worldboss: First Worldboss kill of day/week? Azuregos/Doomwalker",
    [85168] = "Anniversary Worldboss: Second Worldboss kill of day/week? Lord Kazzak",
    [84614] = "Khaz Algar Worldboss killed? Aggregation of Horrors",
    [83280] = "Related to Spark of Omens, weekly",
    [84819] = "Looting Zekvir Hulking Raptorial Claw in Waterworks Tier 8",
    [84818] = "Looting Zekvir Hulking Raptorial Claw in Kriegval's Rest Tier 8",
    [86325] = "Zekvirs Lair kill?",
    [86873] = "Sidestreet Sluice Tier 11 (Overcharged, Bountiful) clear + finished Delvers Journey Season 2?",

    [85463] = "Renown: The Cartels of Undermine Level 2",
    [86371] = "Looted Delver's Bounty (weekly)",
    [87286] = "Excavation Site 9: The Underpin invasion (triggered), 2nd invasion that week",
    [85395] = "Fractured Spark of Fortunes related 5/x?",
    [86695] = "First daily Pristine Mysterious Satchel",
    [90134] = "Pristine Mysterious Satchel? mail feet? epic item? Fortuitous Satchel?",
    [90752] = "First daily Bottle of Mysterious Wisdom attempt",
    [87510] = "Dastardly Duos: First completion? (account)",
    [90775] = "Dastardly Duos: Awarded after turning in Who are the Dastardly Duos (86503) (account)",
    [87527] = "Dastardly Duos: Gained after getting Duos Underdog achievement (account)",

    [87381] = "Horrific Visions Revisited: Stormwind on completion / Alleria kill (Dwarven District, Trade District fully cleared)",
    [88906] = "Horrific Visions Revisited: Stormwind on completion / Alleria kill (Dwarven District, Trade District fully cleared)",

    [87387] = "Horrific Visions Revisited: Stormwind full clear: Veteran vendor unlock?",
    [88907] = "Horrific Visions Revisited: Stormwind full clear: Long Night Mask dropped?",
    [87427] = "Horrific Visions Revisited: Mage District / Valley of Wisdom clear",

    [87389] = "Horrific Visions Revisited: Stormwind 2nd full clear?",
    [88905] = "Horrific Visions Revisited: Stormwind 2nd full clear?",

    [87382] = "Horrific Visions Revisited: Full clear with 1 mask",
    [88908] = "Horrific Visions Revisited: Full clear with 1 mask",

    [87383] = "Horrific Visions Revisited: Full clear with 2 masks",
    [88909] = "Horrific Visions Revisited: Full clear with 2 masks",

    [87384] = "Horrific Visions Revisited: Full clear with 3 masks",
    [88910] = "Horrific Visions Revisited: Full clear with 3 masks",

    [87385] = "Horrific Visions Revisited: Full clear with 4 masks",
    [88911] = "Horrific Visions Revisited: Full clear with 4 masks",

    [87386] = "Horrific Visions Revisited: Full clear with 5 masks",
    [88912] = "Horrific Visions Revisited: Full clear with 5 masks",

    [87429] = "Horrific Visions Revisited: Corrupted area clear?",
    [87430] = "Horrific Visions Revisited: Lost area clear?",
    
    [86407] = "Underpin Tier ? defeated?",
    [86439] = "Underpin Tier ? defeated??",
}

PrintQuests.ConfidentlyNamedTrackingQuests = {
    -----------------------------------------------------------------------------------------------------------------------
    -- Darkmoon Faire
    [29484] = "Darkmoon Faire: Cooking - Putting the Crunch in the Frog",
    [29466] = "Darkmoon Faire: Fishing - Spoilin' for Salty Sea Dogs",
    [29467] = "Darkmoon Faire: Engineering - Talkin' Tonks",
    [29469] = "Darkmoon Faire: Mining - Rearm, Reuse, Recycle",

    -----------------------------------------------------------------------------------------------------------------------
    -- Love is in the Air
    [74957] = "Love is in the Air: Increased X-45 Heartbreaker Droprate (daily, accwide)",
    [86172] = "Love is in the Air: Increased Love Witch's Sweeper Droprate (daily, accwide)",

    -----------------------------------------------------------------------------------------------------------------------
    -- Midsummer
    [83134] = "Midsummer: cosmetic weapon drop rate from Satchel of Chilled Goods (daily, account)",

    -----------------------------------------------------------------------------------------------------------------------
    -- Timewalking
    [78204] = "Turbulent Timeways: Have 5 stacks of Mastery of Timeways",
    [85877] = "Turbulent Timeways II: Have 5 stacks of Mastery of Timeways",
    [89211] = "Turbulent Timeways III: Have 5 stacks of Mastery of Timeways",

    ------------------------------------------------------------------------------------------------------------------------
    -- Greedy Emissary
    [91079] = "Greedy Emissary: Opened Hellcaller Chest 1/10 (weekly, account)",
    [91080] = "Greedy Emissary: Opened Hellcaller Chest 2/10 (weekly, account)",
    [91081] = "Greedy Emissary: Opened Hellcaller Chest 3/10 (weekly, account)",
    [91082] = "Greedy Emissary: Opened Hellcaller Chest 4/10 (weekly, account)",
    [91083] = "Greedy Emissary: Opened Hellcaller Chest 5/10 (weekly, account)",
    [91166] = "Greedy Emissary: Opened Hellcaller Chest 6/10 (weekly, account)",
    [91167] = "Greedy Emissary: Opened Hellcaller Chest 7/10 (weekly, account)",
    [91168] = "Greedy Emissary: Opened Hellcaller Chest 8/10 (weekly, account)",
    [91169] = "Greedy Emissary: Opened Hellcaller Chest 9/10 (weekly, account)",
    [91170] = "Greedy Emissary: Opened Hellcaller Chest 10/10 (weekly, account)",
    [91091] = "Greedy Emissary: Looted Blood-Wrapped Treasure Bag",
    [91092] = "Greedy Emissary: Looted Treasure Nabbin' Bag",
    [76215] = "Greedy Emissary: Killed Treasure Goblin, daily",
    [76216] = "Greedy Emissary: Tyraels Charger Bonus Loot / first Goblin kill, daily",

    ------------------------------------------------------------------------------------------------------------------------
    -- Dastardly Duos
    [90459] = "Dastardly Duos: Podium Upgrade: Scrappiest",
    [90460] = "Dastardly Duos: Podium Upgrade: Longest Survival Run",
    [90461] = "Dastardly Duos: Podium Upgrade: Longest Time in Spotlights",
    [90462] = "Dastardly Duos: Podium Upgrade: Most Yards Traveled",
    [90463] = "Dastardly Duos: Podium Upgrade: Scrappy",
    [90464] = "Dastardly Duos: Podium Upgrade: Current Survival Run Length",
    [90465] = "Dastardly Duos: Podium Upgrade: Time in Spotlight Last Game",
    [90466] = "Dastardly Duos: Podium Upgrade: Yards Moved Last Game",

    -----------------------------------------------------------------------------------------------------------------------
    -- Pandaria Intro
    [37186] = "The Art of War",
    [37193] = "The King's Command",

    -----------------------------------------------------------------------------------------------------------------------
    -- Legion Intro
    [44659] = "Skip the Legion Introductory quests",

    -----------------------------------------------------------------------------------------------------------------------
    -- Artifact Campaign
    [40621] = "Choose Beast Mastery Legendary Weapon questchain",
    [40619] = "Choose Survival Legendary Weapon questchain",
    [40620] = "Choose Marksmanship Legendary Weapon questchain",
    [40708] = "Choose Holy (Priest) Legendary weapon questchain",
    [40707] = "Choose Shadow Legendary weapon questchain",
    [40709] = "Choose Discipline Legendary weapon questchain",

    -----------------------------------------------------------------------------------------------------------------------
    -- Rogue Orderhall
    [50804] = "Rogue Orderhall: Entered Hall of Shadows for the first time",

    -----------------------------------------------------------------------------------------------------------------------
    -- Mardum
    [40232] = "Voras Silk Drape looted",
    [40301] = "Lekos Leash looted",
    [40251] = "Inquisitors Glowering Eye looted",
    [40910] = "Mardum treasure: Small Treasure Chest - Vault of the Betrayer",
    [40915] = "Mardum treasure: Small Treasure Chest - The Demon Ward",
    [40916] = "Mardum treasure: Small Treasure Chest - Chamber of Night",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Return to Karazhan
    [45393] = "Return to Karazhan: Moroes encounter end scene played",
    [45394] = "Return to Karazhan: Maiden of Virtue encounter end scene played",
    [45395] = "Return to Karazhan: Shade of Medivh encounter end scene played",
    [45396] = "Return to Karazhan: Mana Devourer encounter end scene played",
    
    -----------------------------------------------------------------------------------------------------------------------
    -- Battle for Azeroth
    [90909] = "Ensemble: Ashvane Smuggler's Attire",
    [90925] = "Ensemble: Bloodsail Smuggler's Attire",
    [90939] = "Ensemble: Golden Fleet's Sailing Garb",
    [90940] = "Ensemble: Zocalo Merchant's Wear",

    -----------------------------------------------------------------------------------------------------------------------
    -- Exiles Reach
    [58883] = "Stitched Leather Boots looted",
    [59139] = "Spider-Eye Ring looted",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Dragonriding Cosmetics
    [79112] = "Used Winding Slitherdrake: Lunar Festival Armor",
    [82167] = "Used Delver's Dirigible Schematic: Front-Mounted Propeller",
    [82168] = "Used Delver's Dirigible Schematic: Drill",
    [82170] = "Used Delver's Dirigible Schematic: Front-Mounted Lantern",
    [82171] = "Used Delver's Dirigible Schematic: Wing-Mounted Propeller",
    [82173] = "Used Delver's Dirigible Schematic: Turbine",
    [82176] = "Used Delver's Dirigible Schematic: Lantern Wing",
    [82179] = "Used Delver's Dirigible Schematic: Exhaust",
    [82180] = "Used Delver's Dirigible Schematic: Spoiler",
    [82181] = "Used Delver's Dirigible Schematic: Empennage",
    [82182] = "Used Delver's Dirigible Schematic: Glider",
    [82183] = "Used Delver's Dirigible Schematic: Rotor Blades",
    [82185] = "Used Delver's Dirigible Schematic: Zeppelin",
    [82187] = "Used Delver's Dirigible Schematic: Brown Paint",
    [82190] = "Used Delver's Dirigible Schematic: White Paint",
    [83308] = "Used Delver's Dirigible Schematic: Void",
    [85175] = "Used Delver's Gob-Trotter Schematic: Harpoon",
    [85177] = "Used Delver's Gob-Trotter Schematic: Flamethrower",
    [85179] = "Used Delver's Gob-Trotter Schematic: Pipes",
    [85181] = "Used Delver's Gob-Trotter Schematic: Balloon",
    [85183] = "Used Delver's Gob-Trotter Schematic: Green",
    [86198] = "Used Delver's Dirigible Schematic: Pale Paint",
    [86199] = "Used Delver's Dirigible Schematic: Arathi Decal",
    [86296] = "Used Delver's Gob-Trotter Schematic: Gold",

    -----------------------------------------------------------------------------------------------------------------------
    -- Dornogal
    [81519] = "Learned Lilac Educator's Knowledge",
    [81520] = "Learned Leafy Educator's Knowledge",
    [81521] = "Learned Cobalt Educator's Knowledge",
    [81522] = "Learned Midnight Educator's Knowledge",
    [81523] = "Learned Sandy Quotidian Wear",
    [81524] = "Learned Maroon Quotidian Wear",
    [81525] = "Learned Earthy Quotidian Wear",
    [81526] = "Learned Umber Quotidian Wear",
    [81527] = "Learned Taupe Quotidian Wear",
    [81528] = "Learned Vermillion Patron's Elegance",
    [81529] = "Learned Royal Patron's Elegance",
    [81530] = "Learned Verdant Patron's Elegance",
    [81531] = "Learned Celestial Patron's Elegance",
    [81532] = "Learned Court Patron's Elegance",
    [81533] = "Learned Versatile Peddler's Trinkets (Teal)",
    [81534] = "Learned Arcane Peddler's Trinkets (Purple)",
    [81535] = "Learned Curious Peddler's Trinkets (Green)",
    [81536] = "Learned Peculiar Peddler's Trinkets (Blue)",
    [81537] = "Learned Occult Peddler's Trinkets (Black)",
    [83450] = "Archives: Seeking History (ID: 82679) 1/5 story unlocked",
    [83460] = "Archives: Seeking History (ID: 82679) 2/5 story unlocked",
    [83462] = "Archives: Seeking History (ID: 82679) 3/5 story unlocked",
    [83463] = "Archives: Seeking History (ID: 82679) 4/5 story unlocked",
    [83464] = "Archives: Seeking History (ID: 82679) 5/5 story unlocked",
    [85156] = "Angorla stay a while and listen",
    [85103] = "Apprentice Tanmar stay a while and listen",
    [84009] = "Alleria Stay a while and listen after The Fleet Arrives",
    [84345] = "Turalyon Stay a while and listen after Embassies and Envoys",
    [82461] = "Dagran Thaurissan II Stay a while and listen in The Archive",
    [84814] = "Dagran Thaurissan II Stay a while and listen in Vault of Memory",
    [85682] = "Magni Bronzebeard Stay a while and listen in front of The Archive",
    [82542] = "Rooktender Lufsela Stay a while and listen in front of Thrall, Shraubendre",
    [84813] = "Rooktender Lufsela Stay a while and listen in Dhar Oztan",
    [86400] = "Received free Carved Undermine Crest for Crest Transmutation (86401)",
    [86878] = "Used Nightfall Sanctum Campsite",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Severed Threads
    [84539] = "Severed Threads: Renown 22",
    -- The Vizier
    [81605] = "Severed Threads - The Vizier: Reached Acquiantance (1/8) reputation",
    [81606] = "Severed Threads - The Vizier: Reached Crony (2/8) reputation",
    [81607] = "Severed Threads - The Vizier: Reached Accomplice (3/8) reputation",
    -- missing Collaborator 4/8
    [84534] = "Severed Threads - The Vizier: Reached Accessory (5/8) reputation",
    [84535] = "Severed Threads - The Vizier: Reached Abettor (6/8) reputation",
    [84536] = "Severed Threads - The Vizier: Reached Conspirator (7/8) reputation",
    [84537] = "Severed Threads - The Vizier: Reached Mastermind (8/8) reputation",
    -- The Weaver
    [81597] = "Severed Threads - The Weaver: Reached Acquiantance (1/8) reputation",
    -- Crony 2/8 has 2 tracking quests, ref UnsurelyNamedTrackingQuests
    [81599] = "Severed Threads - The Weaver: Reached Accomplice (3/8) reputation",
    [81600] = "Severed Threads - The Weaver: Reached Collaborator (4/8) reputation",
    [84538] = "Severed Threads - The Weaver: Reached Accessory (5/8) reputation",
    -- missing Abettor 6/8
    [84540] = "Severed Threads - The Weaver: Reached Conspirator (7/8) reputation",
    [84541] = "Severed Threads - The Weaver: Reached Mastermind (8/8) reputation",
    -- The General
    [81601] = "Severed Threads - The General: Reached Acquiantance (1/8) reputation",
    -- Crony 2/8 has 2 tracking quests, ref UnsurelyNamedTrackingQuests
    [81603] = "Severed Threads - The General: Reached Accomplice (3/8) reputation",
    [81604] = "Severed Threads - The General: Reached Collaborator (4/8) reputation",
    [84530] = "Severed Threads - The General: Reached Accessory (5/8) reputation",
    [84531] = "Severed Threads - The General: Reached Abettor (6/8) reputation",
    [84532] = "Severed Threads - The General: Reached Conspirator (7/8) reputation",
    [84533] = "Severed Threads - The General: Reached Mastermind (8/8) reputation",
    [80545] = "Severed Threads: Weekly Pact selected: The General",
    [80544] = "Severed Threads: Weekly Pact selected: The Weaver",
    [80546] = "Severed Threads: Weekly Pact selected: The Vizier",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Awakening The Machine
    [84631] = "Awakening The Machine: Wave 5/20 cleared",
    [84632] = "Awakening The Machine: Wave 10/20 cleared",
    [84633] = "Awakening The Machine: Wave 15/20 cleared",
    [84634] = "Awakening The Machine: Wave 20/20 cleared",
    [84644] = "Awakening The Machine: Awakened Cache looted (right)",
    [84642] = "Awakening The Machine: Awakened Cache looted (front left)",
    [84646] = "Awakening The Machine: Awakened Cache looted (back left)",
    [84647] = "Awakening The Machine: Awakened Cache looted (back center)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Alchemy
    [81898] = "Alchemy, Bulk Production 20/25 Khaz Algar trait: First flask crafted (daily)",
    [82388] = "Alchemy, Bulk Production 20/25 Khaz Algar trait: First potion crafted (daily)",
    [83253] = "Alchemy: Alchemical Sediment looted (weekly)",
    [83255] = "Alchemy: Deepstone Crucible looted (weekly)",
    [83725] = "Alchemy: Algari Treatise on Alchemy used (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Blacksmithing
    [83726] = "Blacksmithing: Algari Treatise on Blacksmithing used (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Mining
    [83054] = "Mining: Slab of Slate 1/5 looted (weekly)",
    [83053] = "Mining: Slab of Slate 2/5 looted (weekly)",
    [83052] = "Mining: Slab of Slate 3/5 looted (weekly)",
    [83051] = "Mining: Slab of Slate 4/5 looted (weekly)",
    [83050] = "Mining: Slab of Slate 5/5 looted (weekly)",
    [83049] = "Mining: Erosion-Polished Slate looted (weekly)",
    [80354] = "Mining: First Rich Aqirite looted",
    [80355] = "Mining: First Rich Ironclaw looted",
    [80356] = "Mining: First Bismuth Seam looted",
    [80357] = "Mining: First Aqirite Seam looted",
    [80358] = "Mining: First Ironclaw Seam looted",
    [80359] = "Mining: First Crystallized Bismuth looted",
    [80361] = "Mining: First Crystallized Ironclaw looted",
    [80362] = "Mining: First Weeping Bismuth looted",
    [80363] = "Mining: First Weeping Aqirite looted",
    [80365] = "Mining: First EZ-Mine Bismuth looted",
    [80367] = "Mining: First EZ-Mine Ironclaw looted",
    [80368] = "Mining: First camouflaged Bismuth looted",
    [80369] = "Mining: First camouflaged Aqirite looted",
    [80370] = "Mining: First camouflaged Ironclaw looted",
    [80371] = "Mining: First Webbed Bismuth looted",
    [80372] = "Mining: First Webbed Aqirite looted",
    [80373] = "Mining: First Webbed Ironclaw looted",
    [83907] = "Mining: Dornogal Chisel treasure looted",
    [81391] = "Mining Book: Exceptional Miner's Notes used",
    [83062] = "Mining Book: Machine-Learned Mining Notes used",
    [81392] = "Mining Book: Pristine Miner's Notes used",
    [83733] = "Mining Book: Algari Treatise on Mining used weekly",
    [82614] = "Mining Book: A Rocky Start used",
    [85742] = "Mining Book: Undermine Treatise on Mining used",
    [82317] = "Mastering the Mysterious: Unlocked 2nd Charge of Overload Empowered Deposit",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Enchanting
    [84290] = "Enchanting: Disenchant Fleeting Arcane Manifestation 1/5 (weekly)",
    [84291] = "Enchanting: Disenchant Fleeting Arcane Manifestation 2/5 (weekly)",
    [84292] = "Enchanting: Disenchant Fleeting Arcane Manifestation 3/5 (weekly)",
    [84293] = "Enchanting: Disenchant Fleeting Arcane Manifestation 4/5 (weekly)",
    [84294] = "Enchanting: Disenchant Fleeting Arcane Manifestation 5/5 (weekly)",
    [84295] = "Enchanting: Disenchant Gleaming Telluric Crystal (weekly)",
    [83727] = "Enchanting: Algari Treatise on Enchanting used (weekly)",
    [83258] = "Enchanting: Powdered Fulgurance looted (weekly)",
    [83259] = "Enchanting: Crystalline Repository looted (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Engineering
    [83261] = "Engineering: Earthen Induction Coil looted (weekly)",
    [83260] = "Engineering: Rust-Locked Mechanism looted (weekly)",
    [84229] = "Engineering Book: Faded Engineer Scriblings used",
    [83063] = "Engineering Book: Machine-Learned Engineering Notes used",
    [84230] = "Engineering Book: Exceptional Engineer's Notes used",
    [84231] = "Engineering Book: Pristine Engineer's Scribblings used",
    [85737] = "Engineering Book: Undermine Treatise on Engineering used",
    [83728] = "Engineering Book: Algari Treatise on Engineering used weekly",
    [81355] = "Engineering First Time Craft: Convincingly Realistic Jumper Cables",
    [81356] = "Engineering First Time Craft: Algari Repair Bot 11O",
    [81319] = "Engineering First Time Craft: Bismuth Miner's Headgear",
    [81293] = "Engineering First Time Craft: Algari Competitor's Plate Goggles",
    [81387] = "Engineering First Time Craft: Dredger's Goggles",
    [81365] = "Engineering First Time Craft: Spelunker's Goggles",
    [81364] = "Engineering First Time Craft: Acolyte's Goggles",
    [81352] = "Engineering First Time Craft: Energy Redistribution Beacon",
    [81353] = "Engineering First Time Craft: Irresistable Red Button",
    [81329] = "Engineering First Time Craft: Chaos Circuit",
    [81342] = "Engineering First Time Craft: Serrated Cogwheel",
    [81350] = "Engineering First Time Craft: Pouch of Pocket Grenades",
    [81388] = "Engineering First Time Craft: 4UT0-41M3R",
    [81311] = "Engineering First Time Craft: Spring-Loaded Bismuth Fabric Cutters",
    [81332] = "Engineering First Time Craft: Potion Bomb of Recovery",
    [81347] = "Engineering First Time Craft: Blame Redirection Device",
    [81315] = "Engineering First Time Craft: Bismuth Fisherfriend",
    [81345] = "Engineering First Time Craft: Adjustable Cogwheel",
    [81313] = "Engineering First Time Craft: Bismuth Brainwave Projector",
    [81349] = "Engineering First Time Craft: Complicated Fuse Box",
    [81317] = "Engineering First Time Craft: Lapidary's Bismuth Clamps",
    [81331] = "Engineering First Time Craft: Potion Bomb of Speed",
    [81290] = "Engineering First Time Craft: Algari Competitor's Cloth Goggles",
    [81308] = "Engineering First Time Craft: Venting Vambraces",
    [81346] = "Engineering First Time Craft: Recalibrated Safety Switch",
    [81343] = "Engineering First Time Craft: Overclocked Cogwheel",
    [81351] = "Engineering First Time Craft: Concealed Chaos Module",
    [81320] = "Engineering First Time Craft: Aqirite Miner's Headgear",
    [81324] = "Engineering First Time Craft: Miner's Aqirite Hoard",
    [81316] = "Engineering First Time Craft: Aqirite Fisherfriend",
    [81341] = "Engineering First Time Craft: P.0.W. x2",
    [81314] = "Engineering First Time Craft: Aqirite Brainwave Projector",
    [81307] = "Engineering First Time Craft: Blasting Bracers",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Fishing
    [82896] = "Fishing: First Dilly-Dally Dace looted",
    [82897] = "Fishing: First Bloody Perch looted",
    [82898] = "Fishing: First Crystalline Sturgeon looted",
    [82899] = "Fishing: First Bismuth Bitterling looted",
    [82900] = "Fishing: First Nibbling Minnow looted",
    [82902] = "Fishing: First Goldengill Trout looted",
    [82903] = "Fishing: First Specular Rainbowfish looted",
    [82904] = "Fishing: First Quiet River Bass looted",
    [82905] = "Fishing: First Dornish Pike looted",
    [82906] = "Fishing: First Roaring Anglerseeker looted",
    [82907] = "Fishing: First Arathor Hammerfish looted",
    [82909] = "Fishing: First Kaheti Slum Shark looted",
    [82911] = "Fishing: First Sanguine Dogfish looted",
    [82912] = "Fishing: First Spiked Sea Raven looted",
    [82914] = "Fishing: First Cursed Ghoulfish looted",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Herbalism
    [79907] = "Herbalism: First Lush Mycobloom looted",
    [79914] = "Herbalism: First Lush Luredrop looted",
    [79915] = "Herbalism: First Crystallized Luredrop looted",
    [79917] = "Herbalism: First Irradiated Luredrop looted",
    [79920] = "Herbalism: First Orbinid looted",
    [79921] = "Herbalism: First Lush Orbinid looted",
    [79922] = "Herbalism: First Crystallized Orbinid looted",
    [79926] = "Herbalism: First Sporefused Orbinid looted",
    [79928] = "Herbalism: First Lush Blessing Blossom looted",
    [79929] = "Herbalism: First Crystallized Blessing Blossom looted",
    [79930] = "Herbalism: First Irradiated Blessing Blossom looted",
    [92132] = "Herbalism: First Phantom Bloom looted",
    [92133] = "Herbalism: First Lush Phantom Bloom looted",
    [81416] = "Herbalism: Deepgrove Petal 1/5 looted (weekly)",
    [81417] = "Herbalism: Deepgrove Petal 2/5 looted (weekly)",
    [81418] = "Herbalism: Deepgrove Petal 3/5 looted (weekly)",
    [81419] = "Herbalism: Deepgrove Petal 4/5 looted (weekly)",
    [81420] = "Herbalism: Deepgrove Petal 5/5 looted (weekly)",
    [81421] = "Herbalism: Deepgrove Rose looted (weekly)",
    [83729] = "Herbalism: Algari Treatise on Herbalism used (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Inscription
    [83730] = "Inscription: Algari Treatise on Inscription used (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Jewelcrafting
    [83731] = "Jewelcrafting: Algari Treatise on Jewelcrafting used (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Leatherworking
    [80913] = "Leatherworking First Time Craft: Spelunker's Leather Bands",
    [80907] = "Leatherworking First Time Craft: Spelunker's Leather Footpads",
    [80906] = "Leatherworking First Time Craft: Spelunker's Leather Jerkin",
    [80921] = "Leatherworking First Time Craft: Tracker's Chitin Cuffs",
    [80915] = "Leatherworking First Time Craft: Tracker's Chitin Galoshes",
    [80914] = "Leatherworking First Time Craft: Tracker's Chitin Hauberk",
    [80942] = "Leatherworking First Time Craft: Hideseeker's Hat",
    [83732] = "Leatherworking: Algari Treatise on Leatherworking used (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Skinning
    [83734] = "Skinning: Algari Treatise on Skinning used (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Tailoring
    [83735] = "Tailoring: Algari Treatise on Tailoring used (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- 20th Anniversary
    [86282] = "20th Anniversary Blackrock Depths Miniboss: Pyromancer Loregrain killed LFR",
    [86285] = "20th Anniversary Blackrock Depths Miniboss: Pyromancer Loregrain killed Normal",
    [86278] = "20th Anniversary Blackrock Depths Miniboss: High Interrogator Gerstahn killed LFR",
    [86289] = "20th Anniversary Blackrock Depths Miniboss: High Interrogator Gerstahn killed Normal",
    [86290] = "20th Anniversary Blackrock Depths Miniboss: High Interrogator Gerstahn killed Heroic",
    [86279] = "20th Anniversary Blackrock Depths Miniboss: Houndmaster Grebmar killed LFR",
    [86288] = "20th Anniversary Blackrock Depths Miniboss: Houndmaster Grebmar killed Normal",
    [86291] = "20th Anniversary Blackrock Depths Miniboss: Houndmaster Grebmar killed Heroic",
    [86280] = "20th Anniversary Blackrock Depths Miniboss: Fineous Darkvire killed LFR",
    [86287] = "20th Anniversary Blackrock Depths Miniboss: Fineous Darkvire killed Normal",
    [86292] = "20th Anniversary Blackrock Depths Miniboss: Fineous Darkvire killed Heroic",
    [86281] = "20th Anniversary Blackrock Depths Miniboss: Phalanx killed LFR",
    [86286] = "20th Anniversary Blackrock Depths Miniboss: Phalanx killed Normal",
    [86293] = "20th Anniversary Blackrock Depths Miniboss: Phalanx killed Heroic",
    [84665] = "20th Anniversary: The Originals / Timely Gate Crashers turnin",
    [60214] = "Anniversary Worldboss: Doomwalker Kill",
    [84282] = "Anniversary Worldboss: Sha of Anger Kill",
    [84256] = "Anniversary Worldboss: Archavon the Stone Watcher Kill",
    [47462] = "Anniversary Worldboss: Azuregos Kill",
    [47461] = "Anniversary Worldboss: Lord Kazzak Kill",
    [47463] = "Anniversary Worldboss: Dragon of Nightmare Kill",
    [86202] = "Opened first Bronze Celebration Chest of the week",
    [85661] = "Bought first T2 Set (account)",
    [85828] = "Bought second T2 Set (account)",
    [85841] = "Learned Death Knight T2 Set (account)",
    [85842] = "Learned Demon Hunter T2 Set (account)",
    [85843] = "Learned Druid T2 Set (account)",
    [85844] = "Learned Evoker T2 Set (account)",
    [85845] = "Learned Hunter T2 Set (account)",
    [85846] = "Learned Mage T2 Set (account)",
    [85847] = "Learned Monk T2 Set (account)",
    [85848] = "Learned Paladin T2 Set (account)",
    [85849] = "Learned Priest T2 Set (account)",
    [85850] = "Learned Rogue T2 Set (account)",
    [85851] = "Learned Shaman T2 Set (account)",
    [85852] = "Learned Warlock T2 Set (account)",
    [85853] = "Learned Warrior T2 Set (account)",
    [83831] = "Guest Relations completed Tutorial (A Whiff of Help) (accwide)",
    [85414] = "Guest Relations Pirate Gastronomy: Asked Maru about Rogue's thistle",
    [85415] = "Guest Relations Pirate Gastronomy: Asked Maru about Banana rum berries",
    [85416] = "Guest Relations Pirate Gastronomy: Asked Maru about Fire breathing chill sacs",
    [85417] = "Guest Relations Pirate Gastronomy: Asked Maru about Koatini's oil",
    [85418] = "Guest Relations Pirate Gastronomy: Asked Maru about Deadwind catfish",
    [85419] = "Guest Relations Pirate Gastronomy: Asked Maru about Giant growth fish",
    [85420] = "Guest Relations Pirate Gastronomy: Asked Maru about Sholazar nettles",
    [85421] = "Guest Relations Pirate Gastronomy: Asked Maru about Highland crawdaddies",
    [85411] = "Guest Relations Pirate Gastronomy: Asking Bonenose about Cooktholomew",
    [83824] = "Restoring A Grand Tale - Crafted Green Hills of Stranglethorn",
    [84617] = "Alyx enabled harder challenges - unlock call board",
    [83790] = "Celebration Crate #1 - Opened Gerald",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Isle of Dorn
    [79685] = "Isle of Dorn Rare: Sandres the Relicbearer killed daily",
    [81891] = "Isle of Dorn Rare: Malfunctioning Spire killed",
    [81892] = "Isle of Dorn Rare: Springbubble killed daily",
    [81893] = "Isle of Dorn Rare: Bloodmaw killed daily",
    [81894] = "Isle of Dorn Rare: Warphorn killed daily",
    [81907] = "Isle of Dorn Rare: Escaped Cutthroat killed daily",
    [84029] = "Isle of Dorn Rare: Escaped Cutthroat killed weekly reputation",
    [81897] = "Isle of Dorn Rare: Plaguehart killed daily",
    [84026] = "Isle of Dorn Rare: Plaguehart killed weekly reputation",
    [81899] = "Isle of Dorn Rare: Gar'loc killed daily",
    [84028] = "Isle of Dorn Rare: Gar'loc killed weekly reputation",
    [81921] = "Isle of Dorn Rare: Matriarch Charfuria killed daily",
    [84039] = "Isle of Dorn Rare: Matriarch Charfuria killed weekly reputation",
    [81920] = "Isle of Dorn Rare: Clawbreaker K'zithix killed daily",
    [84036] = "Isle of Dorn Rare: Clawbreaker K'zithix killed weekly reputation",
    [81905] = "Isle of Dorn Rare: Flamekeeper Graz killed daily",
    [84034] = "Isle of Dorn Rare: Flamekeeper Graz killed weekly reputation",
    [82204] = "Isle of Dorn Rare: Kereke killed daily",
    [85160] = "Isle of Dorn Rare: Kereke killed weekly reputation",
    [81902] = "Isle of Dorn Rare: Kronolith, Might of the Mountain killed daily",
    [84031] = "Isle of Dorn Rare: Kronolith, Might of the Mountain killed weekly reputation",
    [82205] = "Isle of Dorn Rare: Rotfist killed daily",
    [85161] = "Isle of Dorn Rare: Rotfist killed weekly reputation",
    [81901] = "Isle of Dorn Rare: Tempest Lord Incarnus killed daily",
    [84030] = "Isle of Dorn Rare: Tempest Lord Incarnus killed weekly reputation",
    [84032] = "Isle of Dorn Rare: Shallowshell the Clacker killed weekly reputation",
    [81922] = "Isle of Dorn Rare: Sweetspark the Oozful killed daily",
    [84038] = "Isle of Dorn Rare: Sweetspark the Oozeful killed weekly reputation",
    [81923] = "Isle of Dorn Rare: Tephratennae killed daily",
    [84037] = "Isle of Dorn Rare: Tephratennae killed weekly reputation",
    [81904] = "Isle of Dorn Rare: Twice-Stinger the Wretched killed daily",
    [84033] = "Isle of Dorn Rare: Twice-Stinger the Wretched killed weekly reputation",
    [85159] = "Isle of Dorn Rare: Zovex killed weekly reputation",
    [78619] = "Isle of Dorn Rare: Rustual Titancap killed daily",
    [83093] = "Isle of Dorn: Dog summoned",
    [83094] = "Isle of Dorn: Faithful Dog pet obtained",
    [86818] = "Isle of Dorn: Archmage Aethas Sunreaver at Tranquil Stand stay a while and listen",
    [79585] = "Isle of Dorn Treasure: Offered Dornish Pike x5 to Dalaran Sewer Turtle",
    [79586] = "Isle of Dorn Treasure: Offered Goldengill Trout x1 to Dalaran Sewer Turtle",
    [82255] = "Isle of Dorn Treasure: Dalaran Sewer Turtle (treasure visible)",
    [82716] = "Isle of Dorn Treasure: Dalaran Sewer Turtle",
    [82227] = "Isle of Dorn Treasure: Magical Treasure Chest (treasure visible)",
    [83243] = "Isle of Dorn Treasure: Magical Treasure Chest",
    [82714] = "Isle of Dorn Treasure: Infused Cinderbrew",
    [82287] = "Isle of Dorn Treasure: Jade Pearl",
    [83246] = "Isle of Dorn Treasure: Mosswool Flower (treasure visible)",
    [82251] = "Isle of Dorn Treasure: Mosswool Flower",
    [82715] = "Isle of Dorn Treasure: Web-Wrapped Axe",
    [82134] = "Isle of Dorn Treasure: Weary Water Elemental (pearl turned in)",
    [82252] = "Isle of Dorn Treasure: Mysterious Orb (treasure visible)",
    [83244] = "Isle of Dorn Treasure: Mysterious Orb",
    [82246] = "Isle of Dorn Treasure: Thak's Treasure",
    [84494] = "Isle of Dorn: Looted Emergency Healthstone on quest 78531",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Ringing Deeps
    [80003] = "Ringing Deeps Rare: Disturbed Earthgorger killed daily",
    [84050] = "Ringing Deeps Rare: Disturbed Earthgorger killed weekly reputation",
    [80506] = "Ringing Deeps Rare: Zilthara Rare killed daily",
    [84041] = "Ringing Deeps Rare: Zilthara Rare The Assembly of the Deeps reputation loot (weekly, account)",
    [80536] = "Ringing Deeps Rare: Deepflayer Broodmother Rare killed daily",
    [85162] = "Ringing Deeps Rare: Deepflayer Broodmother Rare The Assembly of the Deeps reputation loot (weekly, account)",
    [80560] = "Ringing Deeps Rare: Cragmund Rare killed daily",
    [84042] = "Ringing Deeps Rare: Cragmund Rare The Assembly of the Deeps reputation loot (weekly, account)",
    [81562] = "Ringing Deeps Rare: Charmonger Rare killed daily",
    [84044] = "Ringing Deeps Rare: Charmonger Rare killed weekly reputation",
    [81511] = "Ringing Deeps Rare: Coalesced Monstrosity Rare killed daily",
    [84045] = "Ringing Deeps Rare: Coalesced Monstrosity Rare killed weekly reputation",
    [81633] = "Ringing Deeps Rare: Lurker of the Deeps Rare killed daily",
    [85163] = "Ringing Deeps Rare: Lurker of the Deeps Rare killed weekly reputation",
    [81648] = "Ringing Deeps Rare: Hungerer of the Deeps Rare killed daily",
    [84048] = "Ringing Deeps Rare: Hungerer of the Deeps Rare killed weekly reputation",
    [81652] = "Ringing Deeps Rare: Spore-Infused Shalewing Rare killed daily",
    [84049] = "Ringing Deeps Rare: Spore-Infused Shalewing Rare killed weekly reputation",
    [80505] = "Ringing Deeps Rare: Candleflyer Captain Rare killed",
    [80547] = "Ringing Deeps Rare: King Splash Rare killed daily",
    [82464] = "Ringing Deeps Chest: Dusty Prospector Chest looted",
    [82820] = "Ringing Deeps Chest: Blocked Intake looted",
    [82052] = "Ringing Deeps: Submerged Sign interacted",
    [83475] = "Ringing Deeps Achievement: Not So Quick Fix - Water Console",
    [83479] = "Ringing Deeps Achievement: Not So Quick Fix - Abyssal Console",
    [83480] = "Ringing Deeps Achievement: Not So Quick Fix - Taelloch Console",
    [83481] = "Ringing Deeps Achievement: Not So Quick Fix - Obsidian Console",
    [83482] = "Ringing Deeps Achievement: Not So Quick Fix - Lost Console",
    [83483] = "Ringing Deeps Achievement: Not So Quick Fix - Earthen Console",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Hallowfall
    [79271] = "Hallowfall Rare: Sloshmuck killed daily",
    [84062] = "Hallowfall Rare: Sloshmuck Hallowfall Arathi reputation loot (weekly, account)",
    [80009] = "Hallowfall Rare: The Taskmaker killed daily",
    [84061] = "Hallowfall Rare: The Taskmaker Hallowfall Arathi reputation loot (weekly, account)",
    [81756] = "Hallowfall Rare: Lytfang the Lost killed daily",
    [84063] = "Hallowfall Rare: Lytfang the Lost Hallowfall Arathi reputation loot (weekly, account)",
    [81761] = "Hallowfall Rare: Grimslice killed",
    [81836] = "Hallowfall Rare: Horror of the Shallows killed (daily)",
    [84065] = "Hallowfall Rare: Horror of the Shallows Hallowfall Arathi reputation loot (weekly, account)",
    [81849] = "Hallowfall Rare: Strength of Beledar killed (daily)",
    [84066] = "Hallowfall Rare: Strength of Beledar Hallowfall Arathi reputation loot (weekly, account)",
    [81882] = "Hallowfall Rare: Pride of Beledar killed (daily)",
    [84068] = "Hallowfall Rare: Pride of Beledar Hallowfall Arathi reputation loot (weekly, account)",
    [82559] = "Hallowfall Rare: Deathpetal (daily)",
    [84053] = "Hallowfall Rare: Deathpetal Hallowfall Arathi reputation loot (weekly, account)",
    [81881] = "Hallowfall Rare: Funglour killed",
    [82066] = "Hallowfall: A Scout's Journal interacted",
    [79081] = "Hallowfall: Flamegard's Hope Achievement daily lockout",
    [81972] = "Hallowfall: Windswept Satchel near Priory of the Sacred Flame looted",
    [82918] = "Hallowfall: Mereldar Fishing Derby catch Bloody Perch (daily, account)",
    [82919] = "Hallowfall: Mereldar Fishing Derby catch Crystalline Sturgeon (daily, account)",
    [82920] = "Hallowfall: Mereldar Fishing Derby catch Bismuth Bitterling (daily, account)",
    [82921] = "Hallowfall: Mereldar Fishing Derby catch Nibbling Minnow (daily, account)",
    [82922] = "Hallowfall: Mereldar Fishing Derby catch Whispering Stargazer (daily, account)",
    [82923] = "Hallowfall: Mereldar Fishing Derby catch Goldengill Trout (daily, account)",
    [82924] = "Hallowfall: Mereldar Fishing Derby catch Specular Rainbowfish (daily, account)",
    [82925] = "Hallowfall: Mereldar Fishing Derby catch Quiet River Bass (daily, account)",
    [82926] = "Hallowfall: Mereldar Fishing Derby catch Dornish Pike (daily, account)",
    [82927] = "Hallowfall: Mereldar Fishing Derby catch Roaring Anglerseeker (daily, account)",
    [82928] = "Hallowfall: Mereldar Fishing Derby catch Arathor Hammerfish (daily, account)",
    [82929] = "Hallowfall: Mereldar Fishing Derby catch Regal Dottyback (daily, account)",
    [82930] = "Hallowfall: Mereldar Fishing Derby catch Kaheti Slum Shark (daily, account)",
    [82931] = "Hallowfall: Mereldar Fishing Derby catch Pale Huskfish (daily, account)",
    [82932] = "Hallowfall: Mereldar Fishing Derby catch Sanguine Dogfish (daily, account)",
    [82933] = "Hallowfall: Mereldar Fishing Derby catch Spiked Sea Raven (daily, account)",
    [82934] = "Hallowfall: Mereldar Fishing Derby catch Queen''s Lurefish (daily, account)",
    [82935] = "Hallowfall: Mereldar Fishing Derby catch Cursed Ghoulfish (daily, account)",
    [82936] = "Hallowfall: Mereldar Fishing Derby catch Awoken Coelacanth (daily, account)",
    [82947] = "Hallowfall: Mereldar Fishing Derby catch Dilly-Dally Dace (daily, account)",
    [82012] = "Hallowfall: Sky-Captains' Sunken Cache - talked to Sky-Captain Dornald",
    [82024] = "Hallowfall: Sky-Captains' Sunken Cache - talked to Sky-Captain Clairmonte",
    [82025] = "Hallowfall: Sky-Captains' Sunken Cache - talked to Sky-Captain Aerthin",
    [82026] = "Hallowfall: Sky-Captains' Sunken Cache - talked to Sky-Captain Onaro",
    [83300] = "Hallowfall: Arathi Loremaster - answered question 1",
    [83301] = "Hallowfall: Arathi Loremaster - answered question 2",
    [83302] = "Hallowfall: Arathi Loremaster - answered question 3",
    [83303] = "Hallowfall: Arathi Loremaster - answered question 4",
    [83304] = "Hallowfall: Arathi Loremaster - answered question 5",
    [83305] = "Hallowfall: Arathi Loremaster - answered question 6",
    [83624] = "Hallowfall: Light's Gambit easy difficulty selected",
    [83625] = "Hallowfall: Light's Gambit medium difficulty selected",
    [83626] = "Hallowfall: Light's Gambit hard difficulty selected",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Hallowfall - Nightfall 11.1.5
    [88680] = "Arathi Champion's Spoils: First time looted Hallowed Tome",
    [88681] = "Arathi Champion's Spoils: First time looted Shining Arathor Insignia",
    [88682] = "Arathi Champion's Spoils: First time looted ring",
    [88683] = "Arathi Champion's Spoils: First time looted neck",
    [88684] = "Arathi Champion's Spoils: First time looted Arathi offhand/shield (if not eligible: random piece) for current class",
    [88685] = "Arathi Champion's Spoils: First time looted Arathi 1h weapon for current class",
    [88686] = "Arathi Champion's Spoils: First time looted Arathi 2h weapon (if not eligible: random piece) for current class",
    [88687] = "Arathi Champion's Spoils: First time looted Arathi cloak for current class",
    [88688] = "Arathi Champion's Spoils: First time looted Arathi wrist for current class",
    [88689] = "Arathi Champion's Spoils: First time looted Arathi waist for current class",
    [88690] = "Arathi Champion's Spoils: First time looted Arathi hands for current class",
    [88691] = "Arathi Champion's Spoils: First time looted Arathi feet for current class",
    [88692] = "Arathi Champion's Spoils: First time looted Arathi chest for current class",
    [88693] = "Arathi Champion's Spoils: First time looted Arathi legs for current class",
    [88694] = "Arathi Champion's Spoils: First time looted Arathi shoulders for current class",
    [88695] = "Arathi Champion's Spoils: First time looted Arathi head for current class",
    [88885] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall head for current class",
    [88886] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall shoulders for current class",
    [88887] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall legs for current class",
    [88888] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall chest for current class",
    [88889] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall feet for current class",
    [88890] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall hands for current class",
    [88891] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall waist for current class",
    [88892] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall wrist for current class",
    [88893] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall cloak",
    [88894] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall 2h weapon (if not eligible: random piece) for current class",
    [88895] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall 1h weapon for current class",
    [88896] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall offhand/shield (if not eligible: random piece) for current class",
    [88897] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall neck",
    [88898] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Nightfall ring",
    [88899] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Shadowed Essence",
    [88900] = "Confiscated Cultist's Bag/Nightfall scenario boss: First time looted Baleful Excerpt",
    [90105] = "Reputation reward from Nighfall scenario at max progress (daily, account)",
    [89273] = "Nighfall Rare: Dissenter Glaivefur reputation bonus (daily)",
    [91150] = "Nighfall Rare: Dissenter Oathland reputation bonus (daily)",
    [91151] = "Nighfall Rare: Whisperer Batalsworn reputation bonus (daily)",
    [91153] = "Nighfall Rare: Dissenter Fervormyt reputation bonus (daily)",
    [91154] = "Nighfall Rare: Dissenter Tailtrek reputation bonus (daily)",
    [91157] = "Nighfall Rare: Dissenter Fortfervor reputation bonus (daily)",
    [91158] = "Nighfall Rare: Dissenter Troosilver reputation bonus (daily)",
    [91159] = "Nighfall Rare: Whisperer Siegesage reputation bonus (daily)",
    [91160] = "Nighfall Rare: Whisperer Warhavuk reputation bonus (daily)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Azj'kahet
    [80559] = "Azj-Kahet Treasure: Weave-Rat Cache",
    [82520] = "Azj-Kahet Treasure: Memory Cache",
    [82525] = "Azj-Kahet Treasure: Concealed Contraband",
    [82527] = "Azj-Kahet Treasure: Weaving Supplies",
    [82529] = "Azj-Kahet Treasure: Nest Egg",
    [82718] = "Azj-Kahet Treasure: Disturbed Soil",
    [82719] = "Azj-Kahet Treasure: Silk-Spun Supplies",
    [82720] = "Azj-Kahet Treasure: Nerubian Offerings",
    [82721] = "Azj-Kahet Treasure: Niffen Stash",
    [82722] = "Azj-Kahet Treasure: Missing Scout's Pack",
    [82727] = "Azj-Kahet Treasure: Trapped Trove",
    [83772] = "Azj-Kahet Treasure: Convoy Treasure",
    [83724] = "Azj-Kahet Achievement: No Harm Ever Came From Reading A Book: Talked to final clone at the end in cave",
    [83741] = "Azj-Kahet Achievement: No Harm Ever Came From Reading A Book: Initialized evil copies",
    [83744] = "Azj-Kahet Achievement: No Harm Ever Came From Reading A Book: Talked to clone in Wildcamp Or'lay",
    [83745] = "Azj-Kahet Achievement: No Harm Ever Came From Reading A Book: Talked to clone in Faerin's Advance",
    [83746] = "Azj-Kahet Achievement: No Harm Ever Came From Reading A Book: Talked to clone in MMarl",
    [83747] = "Azj-Kahet Achievement: No Harm Ever Came From Reading A Book: Talked to clone in The Weaver's Lair",
    [81702] = "Azj-Kahet Rare: Kaheti Silk Hauler killed (daily)",
    [84071] = "Azj-Kahet Rare: Kaheti Silk Hauler The Severed Threads reputation loot (weekly, account)",
    [91162] = "Azj-Kahet Rare: Kaheti Silk Hauler Flame's Radiance reputation loot (daily, account)",
    [82037] = "Azj-Kahet Rare: Umbraclaw Matra killed (daily)",
    [84080] = "Azj-Kahet Rare: Umbraclaw Matra The Severed Threads reputation loot (weekly, account)",
    [91164] = "Azj-Kahet Rare: Umbraclaw Matra Flame's Radiance reputation loot (daily, account)",
    [82077] = "Azj-Kahet Rare: Deepcrawler Tx'kesh killed (daily)",
    [84081] = "Azj-Kahet Rare: Deepcrawler Tx'kesh The Severed Threads reputation loot (weekly, account)",
    [91161] = "Azj-Kahet Rare: Deepcrawler Tx'kesh Flame's Radiance reputation loot (daily, account)",
    [82078] = "Azj-Kahet Rare: Kaheti Bladeguard killed (daily)",
    [84082] = "Azj-Kahet Rare: Kaheti Bladeguard The Severed Threads reputation loot (weekly, account)",
    [91163] = "Azj-Kahet Rare: Kaheti Bladeguard Flame's Radiance reputation loot (daily, account)",
    [81699] = "Azj-Kahet Rare: Webspeaker Grik'ik killed (daily)",
    [91165] = "Azj-Kahet Rare: Webspeaker Grik'ik Flame's Radiance reputation loot (daily, account)",
    [81703] = "Azj-Kahet Rare: XT-Minecrusher 8700 killed (daily)",
    [84072] = "Azj-Kahet Rare: XT-Minecrusher 8700 The Severed Threads reputation loot (weekly, account)",
    [82036] = "Azj-Kahet Rare: Harvester Qixt killed (daily)",
    [84079] = "Azj-Kahet Rare: Harvester Qixt The Severed Threads reputation loot (weekly, account)",
    [82290] = "Azj-Kahet Rare: The One Left (daily)",
    [85167] = "Azj-Kahet Rare: The One Left The Severed Threads reputation loot (account)",
    [81694] = "Azj-Kahet Rare: Stronghold Scouts",
    [81695] = "Azj-Kahet Rare: Abyssal Devourer",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Siren Isle
    [84801] = "Siren Isle Rare: Ghostmaker killed daily",
    [84792] = "Siren Isle Rare: Ikir the Flotsurge killed daily",
    [85403] = "Siren Isle Rare: Tempest Talon killed daily",
    [84798] = "Siren Isle Rare: Slaughtershell killed daily",
    [85405] = "Siren Isle Rare: Zek'hul the shipbreaker killed daily",
    [85404] = "Siren Isle Rare: Brinebough killed daily",
    [84805] = "Siren Isle Rare: Asbjorn the Bloodsoaked killed daily",
    [84794] = "Siren Isle Rare: Wreckwater killed daily",
    [85406] = "Siren Isle Rare: Ksvir the Forgotten killed daily",
    [86933] = "Siren Isle Rare: Snacker killed daily",
    [84796] = "Siren Isle Rare: Grimmgull killed daily",
    [84797] = "Siren Isle Rare: Gunnlord the Sea-Drinker killed daily",
    [84803] = "Siren Isle Rare: Siris the Sea Scorpion killed daily",
    [84802] = "Siren Isle Rare: Coralweaver Calliso killed daily",
    [84795] = "Siren Isle Rare: Bloodbrine killed daily",
    [86779] = "Siren Isle Rare: Shardsong killed daily",
    [84799] = "Siren Isle Rare: Plank-Master Bluebelly daily",
    [84800] = "Siren Isle Rare: Chef Chum Platter daily",
    [86732] = "Siren Isle Chest: Stone Carvers Scramseax looted",
    [86764] = "Siren Isle Treasure: Kul Tiran Lumberer's Hatchet",
    [86766] = "Siren Isle Treasure: Ashvane Issued Workboots",
    [86767] = "Siren Isle Treasure: Minnow's Favorite Blade",
    [86240] = "Siren Isle: Given Well Loved Squeaky Toy to Marmaduke",
    [86566] = "Siren Isle Quest: Snapdragon Progress Update (24h lockout)",
    [86485] = "Siren Isle Quest: complete A Loyal Friend questchain",
    [86373] = "Siren Isle Loot: Teal Snapdragon Treat",
    [85669] = "Siren Isle: obtained Thunderlord's Crackling Citrine - vendor unlock",
    [85670] = "Siren Isle: obtained Undersea Overseer's Citrine - vendor unlock",
    [85671] = "Siren Isle: obtained Squall Sailor's Citrine - vendor unlock",
    [85672] = "Siren Isle: obtained Mariner's Hallowed Citrine - vendor unlock",
    [85673] = "Siren Isle: obtained Old Salt's Bardic Citrine - vendor unlock",
    [85674] = "Siren Isle: obtained Storm Sewer's Citrine - vendor unlock",
    [85675] = "Siren Isle: obtained Windsinger's Runed Citrine - vendor unlock",
    [85676] = "Siren Isle: obtained Stormbringer's Runed Citrine - vendor unlock",
    [85677] = "Siren Isle: obtained Fathomdweller's Runed Citrine - vendor unlock",
    [85707] = "Siren Isle: obtained Legendary Skipper's Citrine - vendor unlock",
    [85708] = "Siren Isle: obtained Seabed Leviathan's Citrine - vendor unlock",
    [85709] = "Siren Isle: obtained Roaring War-Queen's Citrine - vendor unlock",
    [85799] = "Siren Isle Thrayir: Turbulent Runestone used",
    [85800] = "Siren Isle Thrayir: Cyclonic Runestone used",
    [85801] = "Siren Isle Thrayir: Torrential Runestone used",
    [85802] = "Siren Isle Thrayir: Whirling Runestone used",
    [85803] = "Siren Isle Thrayir: Thunderous Runestone used",
    [82139] = "Ensemble: Pink Tropical",
    [82232] = "Ensemble: Pink Tropical Swimwear",
    [86498] = "Ensemble: Rune Scribe's Vestments",
    [86499] = "Ensemble: Bloodscout Outfit",
    [86500] = "Ensemble: Hydraflayer Regalia",
    [86501] = "Ensemble: Tidecrasher Armor",
    [86504] = "Ensemble: Paradise Beach Loungewear",
    [86505] = "Ensemble: Southsea Cruise Loungewear",
    [86506] = "Ensemble: Salvage Rig Garments",
    [86507] = "Ensemble: Rusty Bruiser's Outfit",
    [86508] = "Ensemble: Sun-Soaked Clothing",
    [86532] = "Ensemble: Bilgeswabby's Garb",
    [86533] = "Ensemble: Pilfered Mariner's Garb",
    [86534] = "Ensemble: Salt-Stained Garb",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Undermine
    [85089] = "Undermine Worldboss kill (weekly, character)",
    [89401] = "Undermine Worldboss loot (weekly, account)",
    [85494] = "Undermine Chest: Marooned Floatmingo",
    [85426] = "Undermine Chest: Potent Potable",
    [85495] = "Undermine Chest: Uncracked Cold Ones",
    [85496] = "Undermine Chest: Trick Deck of Cards",
    [85492] = "Undermine Chest: Particularly Nice Lamp",
    [85116] = "Undermine Chest: Muff's Auto-Locker",
    [85115] = "Undermine Chest: Muff's Auto-Locker in Blackwater Marina",
    [85072] = "Undermine Chest: Muff's Auto-Locker in Hovel Hill",
    [85117] = "Undermine Chest: Muff's Auto-Locker in Entrepreneur Inc.",
    [85114] = "Undermine Chest: Muff's Auto-Locker near golf area",
    [85838] = "Undermine Chest: Fireworks Hat 1/2 unlock",
    [85839] = "Undermine Chest: Fireworks Hat 2/2 unlock",
    [85856] = "Undermine Chest: Fireworks Hat looted",
    [85683] = "Undermine Chest: Unexploded Fireworks",
    [85866] = "Undermine Chest: Suspicious Book 1/2 unlock",
    [85867] = "Undermine Chest: Suspicious Book 2/2 unlock",
    [85868] = "Undermine Chest: Suspicious Book looted",
    [85813] = "Undermine Chest: Blackened Dice unlock - Valve used",
    [85814] = "Undermine Chest: Blackened Dice looted",
    [85425] = "Undermine Chest: Unsupervised Takeout looted",
    [85694] = "Undermine Chest: Inert Plunger used",
    [85698] = "Undermine Chest: Exploded Plunger looted",
    [86487] = "Undermine Chest: Crumpled Schematics looted",
    [85858] = "Undermine Chest: Lonely Tub looted",
    [85422] = "Undermine Chest: Abandoned Toolbox looted",
    [85424] = "Undermine Chest: Papa's Prized Putter looted",
    [84951] = "Bilgewater Cartel Contract selected (account, weekly)",
    [84953] = "Venture Co. Cartel Contract selected (account, weekly)",
    [84954] = "Blackwater Cartel Contract selected (account, weekly)",
    [86598] = "Opened Bilgewater's Trove (honored)",
    [86748] = "Opened Bilgewater's Trove (revered)",
    [86749] = "Opened Bilgewater's Trove (exalted)",
    [86751] = "Opened Blackwater's Trove (revered)",
    [86597] = "Opened Blackwater's Trove (exalted)",
    [86753] = "Opened Steamwheedle's Trove (honored)",
    [86754] = "Opened Steamwheedle's Trove (revered)",
    [86596] = "Opened Steamwheedle's Trove (exalted)",
    [86755] = "Opened Venture Co.'s Trove (honored)",
    [86756] = "Opened Venture Co.'s Trove (revered)",
    [86599] = "Opened Venture Co.'s Trove (exalted)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- S.C.R.A.P.
    [87316] = "S.C.R.A.P.: Blackwater Marina done (onetime, per character)",
    [87315] = "S.C.R.A.P.: Emerald Hills Gold Course done (onetime, per character)",
    [87310] = "S.C.R.A.P.: Hovel Hill (North) done (onetime, per character)",
    [87311] = "S.C.R.A.P.: Hovel Hill (South) done (onetime, per character)",
    [87314] = "S.C.R.A.P.: The Heaps done (onetime, per character)",
    [87312] = "S.C.R.A.P.: The Vatworks done (onetime, per character)",
    [87313] = "S.C.R.A.P.: Venturewood done (onetime, per character)",
    [90471] = "S.C.R.A.P.: Half-Empty Bag looted (weekly)",
    [90472] = "S.C.R.A.P.: Dented Crate looted (weekly)",
    [90473] = "S.C.R.A.P.: Uncovered Strongbox looted (weekly)",
    [87282] = "S.C.R.A.P.: Blackwater Marina Half-Empty Bag visible",
    [87281] = "S.C.R.A.P.: Blackwater Marina Dented Crate visible",
    [86268] = "S.C.R.A.P.: Blackwater Marina Uncovered Strongbox visible",
    [87280] = "S.C.R.A.P.: Emerald Hills Golf Half-Empty Bag visible",
    [87279] = "S.C.R.A.P.: Emerald Hills Golf Course Dented Crate visible",
    [86267] = "S.C.R.A.P.: Emerald Hills Golf Course Uncovered Strongbox visible",
    [87276] = "S.C.R.A.P.: Venturewood Half-Empty Bag visible",
    [87275] = "S.C.R.A.P.: Venturewood Dented Crate visible",
    [86265] = "S.C.R.A.P.: Venturewood Uncovered Strongbox visible",
    [87274] = "S.C.R.A.P.: The Vatworks Half-Empty Bag visible",
    [87273] = "S.C.R.A.P.: The Vatworks Dented Crate visible",
    [86264] = "S.C.R.A.P.: The Vatworks Uncovered Strongbox visible",
    [87270] = "S.C.R.A.P.: Hovel Hill (North) Half-Empty Bag visible",
    [87269] = "S.C.R.A.P.: Hovel Hill (North) Dented Crate visible",
    [86262] = "S.C.R.A.P.: Hovel Hill (North) Uncovered Strongbox visible",
    [87272] = "S.C.R.A.P.: Hovel Hill (South) Half-Empty Bag visible",
    [87271] = "S.C.R.A.P.: Hovel Hill (South) Dented Crate visible",
    [86263] = "S.C.R.A.P.: Hovel Hill (South) Uncovered Strongbox visible",
    [87278] = "S.C.R.A.P.: The Heaps Half-Empty Bag visible",
    [87277] = "S.C.R.A.P.: The Heaps Dented Crate visible",
    [86266] = "S.C.R.A.P.: The Heaps Uncovered Strongbox visible",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- C.H.E.T.T.
    [87296] = "C.H.E.T.T.: Received C.H.E.T.T. List",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Liberation of the Undermine
    [88846] = "Liberation of Undermine Trash: LFR Trash Skiggy Muckheimer killed (weekly)",
    [88848] = "Liberation of Undermine Trash: Normal Trash Skiggy Muckheimer killed (weekly)",
    [89479] = "Liberation of Undermine Trash: First Skiggy Muckheimer kill +100 Gallagio Loyalty Rep (weekly)",

    [88859] = "Liberation of Undermine Trash: LFR Trash Globikus killed (weekly)",
    [88861] = "Liberation of Undermine Trash: Normal Trash Globikus killed (weekly)",
    [89482] = "Liberation of Undermine Trash: First Globikus kill +100 Gallagio Loyalty Rep (weekly)",

    [88835] = "Liberation of Undermine Trash: LFR Trash Guk Boomdog killed (weekly)",
    [88833] = "Liberation of Undermine Trash: Normal Trash Guk Boomdog killed (weekly)",

    [88842] = "Liberation of Undermine Trash: LFR Trash King Flamespite killed (weekly)",

    [88838] = "Liberation of Undermine Trash: LFR Trash Professor Boomspark killed (weekly)",

    [89480] = "Liberation of Undermine Trash; First Melbo the Magnificent kill +100 Gallagio Loyalty Rep (weekly)",
    [88849] = "Liberation of Undermine Trash: Heroic Trash Melbo the Magnificent killed (weekly)",

    [89453] = "Liberation of Undermine Boss: Cauldron of Carnage killed (weekly)",
    [89454] = "Liberation of Undermine Boss: Rik Reverb killed (weekly)",
    [89455] = "Liberation of Undermine Boss: Stix Bunkjunker killed (weekly)",
    [89456] = "Liberation of Undermine Boss: Sprocketmonger Lockenstock killed (weekly)",
    [89457] = "Liberation of Undermine Boss: One-Armed Bandit killed (weekly)",
    [89458] = "Liberation of Undermine Boss: Mug'Zee killed (weekly)",
    [89459] = "Liberation of Undermine Boss: Chrome King Gallywix killed (weekly)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Delves
    [82945] = "Bountiful Waterworks completed (daily)",
    [82938] = "Bountiful The Dread Pit completed (daily)",
    [82937] = "Bountiful The Sinkhole completed (daily)",
    [82776] = "Bountiful Tak-Rethan Abyss completed (daily)",
    [82944] = "Bountiful Earthcrawl Mines completed (daily)",
    [82777] = "Bountiful Nightfall Sanctum completed (treasure room opened) (daily)",
    [82942] = "Bountiful The Spiral Weave completed (daily)",
    [82943] = "Bountiful The Underkeep completed (daily)",
    [82941] = "Bountiful Kriegval's Rest completed (daily)",
    [85187] = "Bountiful Excavation Site 9 completed (daily)",
    [82939] = "Bountiful Fungal Folly completed (daily)",
    [78508] = "Bountiful Skittering Breach completed (daily)",
    [85668] = "Bountiful Sidestreet Sluice completed (daily)",
    [83317] = "Council of Dornogal Rep bonus on delve complete (weekly, account)",
    [83318] = "Assembly of the Deeps Rep bonus on delve complete (weekly, account)",
    [83320] = "Hallowfall Arathi Rep bonus on delve complete (weekly, account)",
    [83319] = "Severed Threads Rep bonus on delve complete (weekly, account)",
    [87407] = "The Cartels of Undermine Rep bonus on delve complete (weekly, account)",
    [83456] = "The Waterworks - Sturdy Chest near Waxface looted (account, onetime)",
    -- [xxxxx] = "Earthcrawl Mines - Sturdy Chest near Web General Ab'enar looted (account, onetime)",
    -- [xxxxx] = "Earthcrawl Mines - Sturdy Chest: In square shaped room looted (account, onetime)",
    [83679] = "Skittering Breach - Sturdy Chest in first building looted (account, onetime)",
    [83696] = "Skittering Breach - Sturdy Chest at the edge of building near boss platform (account, onetime)",
    [83663] = "The Underkeep - Sturdy Chest in passage between left and bottom room looted (account, onetime)",
    [83663] = "The Underkeep - Sturdy Chest in Researcher Ven'kex room looted (account, onetime)",
    [83691] = "Myromancer Cavern - Sturdy Chest under water looted (account, onetime)",
    [83672] = "Myromancer Cavern - Sturdy Chest on rock inside water looted (account, onetime)",
    [83455] = "Myromancer Cavern - Sturdy Chest in top right corner of map looted (account, onetime)",
    -- [xxxxx] = "Fungal Folly - Sturdy Chest in top right corner of map looted (account, onetime)",
    [83651] = "Tak-Rethan Abyss - Sturdy Chest above water entrance looted (account, onetime)",
    [83669] = "Tak-Rethan Abyss - Sturdy Chest on left side of map looted (account, onetime)",
    [83686] = "Tak-Rethan Abyss - Sturdy Chest on coral looted (account, onetime)",
    [83688] = "Nightfall Sanctum - Sturdy Chest next to entrance looted (account, onetime)",
    [83701] = "Nightfall Sanctum - Sturdy Chest top left on map, near tower (account, onetime)",
    [86788] = "Sidestreet Sluice - Sturdy Chest in treasure room looted (account, onetime)",
    [86790] = "Sidestreet Sluice - Sturdy Chest in near rare crab, bottom left on map The Pits (account, onetime)",
    [86789] = "Sidestreet Sluice - Sturdy Chest in The High Decks (account, onetime)",
    [83683] = "Kriegvals Rest - Sturdy Chest near checkpoint (account, onetime)",
    [84101] = "Brann reached Level 40 (account, onetime)",
    [84102] = "Brann reached Level 41 (account, onetime)",
    [84103] = "Brann reached Level 42 (account, onetime)",
    [84104] = "Brann reached Level 43 (account, onetime)",
    [84105] = "Brann reached Level 44 (account, onetime)",
    [84106] = "Brann reached Level 45 (account, onetime)",
    [84107] = "Brann reached Level 46 (account, onetime)",
    [84108] = "Brann reached Level 47 (account, onetime)",
    [84109] = "Brann reached Level 48 (account, onetime)",
    [84110] = "Brann reached Level 49 (account, onetime)",
    [83329] = "Brann reached Level 50 (account, onetime)",
    [84111] = "Brann reached Level 51 (account, onetime)",
    [84112] = "Brann reached Level 52 (account, onetime)",
    [84113] = "Brann reached Level 53 (account, onetime)",
    [84114] = "Brann reached Level 54 (account, onetime)",
    [84115] = "Brann reached Level 55 (account, onetime)",
    [84116] = "Brann reached Level 56 (account, onetime)",
    [84117] = "Brann reached Level 57 (account, onetime)",
    [84118] = "Brann reached Level 58 (account, onetime)",
    [84119] = "Brann reached Level 59 (account, onetime)",
    [83330] = "Brann reached Level 60 (account, onetime)",
    [86974] = "Brann reached Level 61 (account, onetime)",
    [86975] = "Brann reached Level 62 (account, onetime)",
    [86976] = "Brann reached Level 63 (account, onetime)",
    [86977] = "Brann reached Level 64 (account, onetime)",
    [86978] = "Brann reached Level 65 (account, onetime)",
    [86979] = "Brann reached Level 66 (account, onetime)",
    [86980] = "Brann reached Level 67 (account, onetime)",
    [86981] = "Brann reached Level 68 (account, onetime)",
    [86982] = "Brann reached Level 69 (account, onetime)",
    [86983] = "Brann reached Level 70 (account, onetime)",
    [86984] = "Brann reached Level 71 (account, onetime)",
    [86985] = "Brann reached Level 72 (account, onetime)",
    [86986] = "Brann reached Level 73 (account, onetime)",
    [86987] = "Brann reached Level 74 (account, onetime)",
    [86988] = "Brann reached Level 75 (account, onetime)",
    [86989] = "Brann reached Level 76 (account, onetime)",
    [86990] = "Brann reached Level 77 (account, onetime)",
    [86991] = "Brann reached Level 78 (account, onetime)",
    [86992] = "Brann reached Level 79 (account, onetime)",
    [86993] = "Brann reached Level 80 (account, onetime)",
    [86324] = "Zekvirs Lair Tier 2 kill (weekly)",
    [86328] = "Delver's Starter Kit bought",
    [86329] = "Delver's Cosmetic Surprise Bag bought",
    [85204] = "Delver's Journey Season 2: Delver's Dirigible Schematic: Flamethrower",
    [85203] = "Delver's Journey Season 2: Delver's Dirigible Schematic: Pipes",
    [85202] = "Delver's Journey Season 2: Delver's Dirigible Schematic: Harpoon",
    [85201] = "Delver's Journey Season 2: Delver's Dirigible Schematic: Balloon",
    [85200] = "Delver's Journey Season 2: Delver's Dirigible Schematic: Green Paint",
    [85210] = "Delver's Journey Season 2: Unlocked Delve-O-Bot 7001",
    [85206] = "Delver's Journey Season 2: Unlocked Warbound Set",
    [85207] = "Delver's Journey Season 2: Unlocked purchaseable Restored Coffer Keys",
    [85205] = "Delver's Journey Season 2: Discounted Restored Coffer Key unlocked",
    [90780] = "Looted Cracked Keystone (242919)",
    [83158] = "Adventurer's Warbound Battlegear dropped (account)",
    [86438] = "Delves Season 2: Opened first purple Nemesis Strongbox and first Underpin invasion (account)",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- D.R.I.V.E.
    [86771] = "D.R.I.V.E.: Paint: Body Roll Blue used",
    [86772] = "D.R.I.V.E.: Paint: Goblin Green used",
    [86773] = "D.R.I.V.E.: Paint: Redlining Red used",
    [86774] = "D.R.I.V.E.: Paint: Yellow Cake Yellow used",
    [85783] = "D.R.I.V.E.: Steamboil used",
    [85784] = "D.R.I.V.E.: Handcrank used",
    [85785] = "D.R.I.V.E.: The Ol' Low-and-Slow used",
    [85786] = "D.R.I.V.E.: The Buzzer used",
    [85787] = "D.R.I.V.E.: Maniacal Melodies used",
    [85788] = "D.R.I.V.E.: The Whole Brass Band used",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Misc
    [39751] = "Classic Timewalking LFG completion",
    [84736] = "1/4 Restored Coffer Key looted of the week",
    [84737] = "2/4 Restored Coffer Key looted of the week",
    [84738] = "3/4 Restored Coffer Key looted of the week",
    [84739] = "4/4 Restored Coffer Key looted of the week",
    [90597] = "Arsenal: Children's Stormwind Guard Weapon Set",
    [90598] = "Arsenal: Children's Orgrimmar Guard Weapon Set",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Mythic+
    [85469] = "First weekly completion of an 8+ Mythic Dungeon",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Horrific Visions
    [58893] = "Horrific Visions: Stormwind Mage District clear",
    [58897] = "Horrific Visions: Stormwind Trade District clear",
    [58890] = "Horrific Visions: Stormwind Old Town clear",
    [58894] = "Horrific Visions: Stormwind Dwarven District clear",
    [58895] = "Horrific Visions: Orgrimmar The Drag clear",
    [58892] = "Horrific Visions: Orgrimmar Valley of Honor clear",
    [58891] = "Horrific Visions: Orgrimmar Valley of Wisdom clear",
    [58896] = "Horrific Visions: Orgrimmar Valley of Spirits clear",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Horrific Visions Revisited
    [87428] = "Horrific Visions Revisited: Ended (completion/fail)",
    [87431] = "Horrific Visions Revisited: Completion",
    [90709] = "Used Warbound Purifying Kit",
    [90710] = "Used Enchanted Warbound Purifying Kit",
    [90129] = "Retrieved Voidfire Deathcycle from Vision",
    [90529] = "Horrific Visions Revisited: Valley of Honor Voidfire Deathcycle reagent unlocked",
    [90530] = "Horrific Visions Revisited: Valley of Wisdom Voidfire Deathcycle reagent unlocked",
    [89472] = "Horrific Visions Revisited: Black Blood Infused Bar reagent looted",
    [90130] = "Voidfire Deathcycle: installed wheels",
    [90131] = "Voidfire Deathcycle: installed seat",
    [90132] = "Voidfire Deathcycle: installed handlebars",
    [90133] = "Voidfire Deathcycle: installed engine",
    [90135] = "Voidfire Deathcycle: installed battery",
    [90136] = "Voidfire Deathcycle: completed (pressed red button)",
    [90523] = "Voidfire Deathcycle: installed exhaust",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- Durable Information Securing Container
    [90945] = "D.I.S.C. Unlocked Charged Bolts",
    [90946] = "D.I.S.C. Unlocked Cauterizing Bolts",
    [90947] = "D.I.S.C. Unlocked Critical Chain",
    [90948] = "D.I.S.C. Unlocked Spark Burst",
    [90949] = "D.I.S.C. Unlocked Static Charge",
    [90950] = "D.I.S.C. Unlocked Electric Current",
    [90951] = "D.I.S.C. Unlocked Charged Touch",
    [90952] = "D.I.S.C. Unlocked Energy Shield",
    [90953] = "D.I.S.C. Unlocked Charged Crystal",

    -- -----------------------------------------------------------------------------------------------------------------------
    -- K'aresh
    [90600] = "Stay awhile and Listen - Xalatath, Alleria and Locus-Walker in Myzas Oasis",
    [85840] = "K'aresh treasure: Sand-Worn Coffer",
    [85837] = "K'aresh treasure: Forlorn Wind Chime",
}
